// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use marker_core::schema::mail::DatabaseMarker as DatabaseMarker;
#[rustfmt::skip]
pub use marker_core::schema::mail::CommitSequence as CommitSequence;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Debug,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
)]
#[rkyv(derive(PartialEq, Eq, PartialOrd, Ord))]
pub struct Topic(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Topics(Vec<Topic>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Description(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordIdentifier(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Rejection(Description);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Limit(Option<Integer>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Entries(Vec<Entry>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ByTopic(std::collections::BTreeMap<Topic, RecordIdentifier>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Entry {
    pub topics: Topics,
    pub description: Description,
    pub agent_name: AgentName,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Query {
    pub topics: Topics,
    pub limit: Limit,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordReceipt {
    pub record_identifier: RecordIdentifier,
    pub database_marker: DatabaseMarker,
    pub commit_sequence: CommitSequence,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordSet {
    pub entries: Entries,
    pub by_topic: ByTopic,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Record(Entry),
    Observe(Query),
    Mark(DatabaseMarker),
    Commit(CommitSequence),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Recorded(RecordReceipt),
    Observed(RecordSet),
    Marked(DatabaseMarker),
    Committed(CommitSequence),
    Rejected(Rejection),
}

#[rustfmt::skip]
impl Topic {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Topic {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Topics {
    pub fn new(payload: Vec<Topic>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<Topic> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<Topic> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<Topic>> for Topics {
    fn from(payload: Vec<Topic>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Description {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Description {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AgentName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for AgentName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RecordIdentifier {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for RecordIdentifier {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Rejection {
    pub fn new(payload: Description) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Description {
        &self.0
    }
    pub fn into_payload(self) -> Description {
        self.0
    }
}
#[rustfmt::skip]
impl From<Description> for Rejection {
    fn from(payload: Description) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Limit {
    pub fn new(payload: Option<Integer>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<Integer> {
        &self.0
    }
    pub fn into_payload(self) -> Option<Integer> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<Integer>> for Limit {
    fn from(payload: Option<Integer>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Entries {
    pub fn new(payload: Vec<Entry>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<Entry> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<Entry> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<Entry>> for Entries {
    fn from(payload: Vec<Entry>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ByTopic {
    pub fn new(payload: std::collections::BTreeMap<Topic, RecordIdentifier>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &std::collections::BTreeMap<Topic, RecordIdentifier> {
        &self.0
    }
    pub fn into_payload(self) -> std::collections::BTreeMap<Topic, RecordIdentifier> {
        self.0
    }
}
#[rustfmt::skip]
impl From<std::collections::BTreeMap<Topic, RecordIdentifier>> for ByTopic {
    fn from(payload: std::collections::BTreeMap<Topic, RecordIdentifier>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn record(payload: Entry) -> Self {
        Self::Record(payload)
    }
    pub fn observe(payload: Query) -> Self {
        Self::Observe(payload)
    }
    pub fn mark(payload: DatabaseMarker) -> Self {
        Self::Mark(payload)
    }
    pub fn commit(payload: CommitSequence) -> Self {
        Self::Commit(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn recorded(payload: RecordReceipt) -> Self {
        Self::Recorded(payload)
    }
    pub fn observed(payload: RecordSet) -> Self {
        Self::Observed(payload)
    }
    pub fn marked(payload: DatabaseMarker) -> Self {
        Self::Marked(payload)
    }
    pub fn committed(payload: CommitSequence) -> Self {
        Self::Committed(payload)
    }
    pub fn rejected(payload: Description) -> Self {
        Self::Rejected(Rejection::new(payload))
    }
}

#[rustfmt::skip]
impl From<Entry> for Input {
    fn from(payload: Entry) -> Self {
        Self::Record(payload)
    }
}

#[rustfmt::skip]
impl From<Query> for Input {
    fn from(payload: Query) -> Self {
        Self::Observe(payload)
    }
}

#[rustfmt::skip]
impl From<DatabaseMarker> for Input {
    fn from(payload: DatabaseMarker) -> Self {
        Self::Mark(payload)
    }
}

#[rustfmt::skip]
impl From<CommitSequence> for Input {
    fn from(payload: CommitSequence) -> Self {
        Self::Commit(payload)
    }
}

#[rustfmt::skip]
impl From<RecordReceipt> for Output {
    fn from(payload: RecordReceipt) -> Self {
        Self::Recorded(payload)
    }
}

#[rustfmt::skip]
impl From<RecordSet> for Output {
    fn from(payload: RecordSet) -> Self {
        Self::Observed(payload)
    }
}

#[rustfmt::skip]
impl From<DatabaseMarker> for Output {
    fn from(payload: DatabaseMarker) -> Self {
        Self::Marked(payload)
    }
}

#[rustfmt::skip]
impl From<CommitSequence> for Output {
    fn from(payload: CommitSequence) -> Self {
        Self::Committed(payload)
    }
}

#[rustfmt::skip]
impl From<Rejection> for Output {
    fn from(payload: Rejection) -> Self {
        Self::Rejected(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct MessageIdentifier(Integer);
#[rustfmt::skip]
impl MessageIdentifier {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(Integer);
#[rustfmt::skip]
impl OriginRoute {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
pub mod schema {
    #[derive(
        rkyv::Archive,
        rkyv::Serialize,
        rkyv::Deserialize,
        Clone,
        Debug,
        PartialEq,
        Eq
    )]
    pub enum Plane<SignalRoot, NexusRoot, SemaRoot> {
        Signal(super::Signal<SignalRoot>),
        Nexus(super::Nexus<NexusRoot>),
        Sema(super::Sema<SemaRoot>),
    }
    impl<SignalRoot, NexusRoot, SemaRoot> Plane<SignalRoot, NexusRoot, SemaRoot> {
        pub fn origin_route(&self) -> super::OriginRoute {
            match self {
                Self::Signal(message) => message.origin_route(),
                Self::Nexus(message) => message.origin_route(),
                Self::Sema(message) => message.origin_route(),
            }
        }
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Signal<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Signal<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Signal<NextRoot> {
        Signal::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod signal {
    pub type Input = super::Input;
    pub type Output = super::Output;
    pub type Signal<Root> = super::Signal<Root>;
}

#[rustfmt::skip]
impl Input {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
