// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;
#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Debug,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
)]
pub struct Bytes(dotos::ByteSequence);
#[rustfmt::skip]
impl Bytes {
    pub fn new(payload: Vec<u8>) -> Self {
        Self(dotos::ByteSequence::new(payload))
    }
    pub fn payload(&self) -> &[u8] {
        self.0.payload()
    }
    pub fn into_payload(self) -> Vec<u8> {
        self.0.into_payload()
    }
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Debug,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
)]
pub struct FixedBytes<const WIDTH: usize>(dotos::FixedByteSequence<WIDTH>);
#[rustfmt::skip]
impl<const WIDTH: usize> FixedBytes<WIDTH> {
    pub fn new(payload: [u8; WIDTH]) -> Self {
        Self(dotos::FixedByteSequence::new(payload))
    }
    pub fn payload(&self) -> &[u8; WIDTH] {
        self.0.payload()
    }
    pub fn into_payload(self) -> [u8; WIDTH] {
        self.0.into_payload()
    }
}

#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
pub use dotos::{DotosDecodeError, DotosEncode, DotosSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Debug,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
)]
#[rkyv(derive(PartialEq, Eq, PartialOrd, Ord))]
pub struct NodeName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NodeConfig(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Service(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Query(Topic);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Topic(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Healthy(Boolean);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ConfigPath(Path);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Digest(Bytes);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Fingerprint(FixedBytes<4>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Cluster {
    pub service_vector: Vec<Service>,
    pub node_config_by_node_name: std::collections::BTreeMap<NodeName, NodeConfig>,
    pub optional_node_config: Option<NodeConfig>,
    pub healthy: Healthy,
    pub config_path: ConfigPath,
    pub digest: Digest,
    pub fingerprint: Fingerprint,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Register(Cluster),
    Observe(Query),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Projected(std::collections::BTreeMap<NodeName, NodeConfig>),
    Listed(Vec<NodeName>),
}

#[rustfmt::skip]
impl NodeName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for NodeName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl NodeConfig {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for NodeConfig {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Service {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Service {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Query {
    pub fn new(payload: Topic) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Topic {
        &self.0
    }
    pub fn into_payload(self) -> Topic {
        self.0
    }
}
#[rustfmt::skip]
impl From<Topic> for Query {
    fn from(payload: Topic) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Topic {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Topic {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Healthy {
    pub fn new(payload: Boolean) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Boolean {
        &self.0
    }
    pub fn into_payload(self) -> Boolean {
        self.0
    }
}
#[rustfmt::skip]
impl From<Boolean> for Healthy {
    fn from(payload: Boolean) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ConfigPath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &Path {
        &self.0
    }
    pub fn into_payload(self) -> Path {
        self.0
    }
}
#[rustfmt::skip]
impl From<Path> for ConfigPath {
    fn from(payload: Path) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Digest {
    pub fn new(payload: Bytes) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Bytes {
        &self.0
    }
    pub fn into_payload(self) -> Bytes {
        self.0
    }
}
#[rustfmt::skip]
impl From<Bytes> for Digest {
    fn from(payload: Bytes) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Fingerprint {
    pub fn new(payload: FixedBytes<4>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &FixedBytes<4> {
        &self.0
    }
    pub fn into_payload(self) -> FixedBytes<4> {
        self.0
    }
}
#[rustfmt::skip]
impl From<FixedBytes<4>> for Fingerprint {
    fn from(payload: FixedBytes<4>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn register(payload: Cluster) -> Self {
        Self::Register(payload)
    }
    pub fn observe(payload: Topic) -> Self {
        Self::Observe(Query::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn projected(payload: std::collections::BTreeMap<NodeName, NodeConfig>) -> Self {
        Self::Projected(payload)
    }
    pub fn listed(payload: Vec<NodeName>) -> Self {
        Self::Listed(payload)
    }
}

#[rustfmt::skip]
impl From<Cluster> for Input {
    fn from(payload: Cluster) -> Self {
        Self::Register(payload)
    }
}

#[rustfmt::skip]
impl From<Query> for Input {
    fn from(payload: Query) -> Self {
        Self::Observe(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::str::FromStr for Input {
    type Err = DotosDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        DotosSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as DotosEncode>::to_dotos(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::str::FromStr for Output {
    type Err = DotosDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        DotosSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as DotosEncode>::to_dotos(self))
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct MessageIdentifier(Integer);
#[rustfmt::skip]
impl MessageIdentifier {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(Integer);
#[rustfmt::skip]
impl OriginRoute {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
pub mod schema {
    #[derive(
        rkyv::Archive,
        rkyv::Serialize,
        rkyv::Deserialize,
        Clone,
        Debug,
        PartialEq,
        Eq
    )]
    pub enum Plane<SignalRoot, NexusRoot, SemaRoot> {
        Signal(super::Signal<SignalRoot>),
        Nexus(super::Nexus<NexusRoot>),
        Sema(super::Sema<SemaRoot>),
    }
    impl<SignalRoot, NexusRoot, SemaRoot> Plane<SignalRoot, NexusRoot, SemaRoot> {
        pub fn origin_route(&self) -> super::OriginRoute {
            match self {
                Self::Signal(message) => message.origin_route(),
                Self::Nexus(message) => message.origin_route(),
                Self::Sema(message) => message.origin_route(),
            }
        }
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Signal<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Signal<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Signal<NextRoot> {
        Signal::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod signal {
    pub type Input = super::Input;
    pub type Output = super::Output;
    pub type Signal<Root> = super::Signal<Root>;
}

#[rustfmt::skip]
impl Input {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
