// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Topic(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Topics(Vec<Topic>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Description(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Summary(Description);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordIdentifier(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Entry {
    pub topics: Topics,
    pub kind: Kind,
    pub description: Description,
    pub magnitude: Magnitude,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Query {
    pub topic: Topic,
    pub kind: Kind,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordSet(Vec<Entry>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum Kind {
    Decision,
    Principle,
    Correction,
    Clarification,
    Constraint,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum Magnitude {
    Minimum,
    VeryLow,
    Low,
    Medium,
    High,
    VeryHigh,
    Maximum,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Record(Entry),
    Observe(Query),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    RecordAccepted(RecordIdentifier),
    RecordsObserved(RecordSet),
}

#[rustfmt::skip]
impl Topic {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Topic {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Topics {
    pub fn new(payload: Vec<Topic>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<Topic> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<Topic> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<Topic>> for Topics {
    fn from(payload: Vec<Topic>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Description {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Description {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Summary {
    pub fn new(payload: Description) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Description {
        &self.0
    }
    pub fn into_payload(self) -> Description {
        self.0
    }
}
#[rustfmt::skip]
impl From<Description> for Summary {
    fn from(payload: Description) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RecordIdentifier {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for RecordIdentifier {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RecordSet {
    pub fn new(payload: Vec<Entry>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<Entry> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<Entry> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<Entry>> for RecordSet {
    fn from(payload: Vec<Entry>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn record(payload: Entry) -> Self {
        Self::Record(payload)
    }
    pub fn observe(payload: Query) -> Self {
        Self::Observe(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn record_accepted(payload: Integer) -> Self {
        Self::RecordAccepted(RecordIdentifier::new(payload))
    }
    pub fn records_observed(payload: Vec<Entry>) -> Self {
        Self::RecordsObserved(RecordSet::new(payload))
    }
}

#[rustfmt::skip]
impl From<Entry> for Input {
    fn from(payload: Entry) -> Self {
        Self::Record(payload)
    }
}

#[rustfmt::skip]
impl From<Query> for Input {
    fn from(payload: Query) -> Self {
        Self::Observe(payload)
    }
}

#[rustfmt::skip]
impl From<RecordIdentifier> for Output {
    fn from(payload: RecordIdentifier) -> Self {
        Self::RecordAccepted(payload)
    }
}

#[rustfmt::skip]
impl From<RecordSet> for Output {
    fn from(payload: RecordSet) -> Self {
        Self::RecordsObserved(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_RECORD: u64 = 0x0000000100000001;
    pub const INPUT_OBSERVE: u64 = 0x0001000100000001;
    pub const OUTPUT_RECORD_ACCEPTED: u64 = 0x0100000100000001;
    pub const OUTPUT_RECORDS_OBSERVED: u64 = 0x0101000100000001;
    pub const HANDSHAKE_REQUEST: u64 = 0xFF00000100000001;
    pub const HANDSHAKE_REPLY: u64 = 0xFF01000100000001;
    pub const ENGINE_REFUSAL: u64 = 0xFF02000100000001;
}

#[rustfmt::skip]
pub enum ContractMarker {}
#[rustfmt::skip]
impl signal_frame::WireContract for ContractMarker {
    const BINDING: signal_frame::ContractBinding = signal_frame::ContractBinding::new(
        match signal_frame::ContractId::try_new(1u32) {
            Ok(contract) => contract,
            Err(_) => panic!("generated contract ID must be nonzero"),
        },
        match signal_frame::WireRevision::try_new(1u16) {
            Ok(revision) => revision,
            Err(_) => panic!("generated wire revision must be nonzero"),
        },
    );
}
#[rustfmt::skip]
/// Why the daemon refused to produce an ordinary reply.
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq
)]
pub enum EngineRefusalReason {
    /// The engine ran and rejected the request with its typed
    /// domain error; the rendered error text is the detail.
    Rejected,
    /// The engine layer could not serve the request at all.
    Unavailable,
}
#[rustfmt::skip]
impl std::fmt::Display for EngineRefusalReason {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Rejected => formatter.write_str("engine rejected the request"),
            Self::Unavailable => formatter.write_str("engine unavailable"),
        }
    }
}
#[rustfmt::skip]
/// The refusal reply a daemon writes when the engine failed, so
/// the caller receives a complete typed frame instead of a closed
/// socket it cannot distinguish from daemon death. The typed
/// engine error stays daemon-side; the wire carries the
/// classification plus the rendered error text.
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineRefusal {
    pub reason: EngineRefusalReason,
    pub detail: String,
}
#[rustfmt::skip]
impl EngineRefusal {
    pub fn rejected(detail: String) -> Self {
        Self {
            reason: EngineRefusalReason::Rejected,
            detail,
        }
    }
    pub fn unavailable(detail: String) -> Self {
        Self {
            reason: EngineRefusalReason::Unavailable,
            detail,
        }
    }
    pub fn encode_bound_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            signal_frame::SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&short_header::ENGINE_REFUSAL.to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    FrameEncode,
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    LegacyHeader { contract_id: u32, wire_revision: u16 },
    ContractMismatch { expected: u32, found: u32 },
    UnsupportedWireRevision { contract_id: u32, expected: u16, found: u16 },
    UnknownRoute { root: u8, variant: u8 },
    RouteBodyMismatch { root: u8, variant: u8, body: &'static str },
    UnexpectedFrameBody { found: &'static str },
    OperationCount { found: usize },
    EngineRefused { refusal: EngineRefusal },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::FrameEncode => {
                formatter.write_str("failed to encode bound signal frame")
            }
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::LegacyHeader { contract_id, wire_revision } => {
                write!(
                    formatter,
                    "legacy unbound signal frame ({contract_id}, {wire_revision})"
                )
            }
            Self::ContractMismatch { expected, found } => {
                write!(
                    formatter,
                    "signal contract mismatch: expected {expected}, found {found}"
                )
            }
            Self::UnsupportedWireRevision { contract_id, expected, found } => {
                write!(
                    formatter,
                    "unsupported wire revision for contract {contract_id}: expected {expected}, found {found}"
                )
            }
            Self::UnknownRoute { root, variant } => {
                write!(formatter, "unknown bound signal route ({root}, {variant})")
            }
            Self::RouteBodyMismatch { root, variant, body } => {
                write!(
                    formatter,
                    "bound signal route ({root}, {variant}) does not carry {body}"
                )
            }
            Self::UnexpectedFrameBody { found } => {
                write!(formatter, "expected one request frame, found {found}")
            }
            Self::OperationCount { found } => {
                write!(formatter, "expected one request operation, found {found}")
            }
            Self::EngineRefused { refusal } => {
                write!(formatter, "{}: {}", refusal.reason, refusal.detail)
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}
#[rustfmt::skip]
impl ContractMarker {
    pub fn handshake_request_frame(request: signal_frame::HandshakeRequest) -> Frame {
        Frame::new(
            signal_frame::WireRoute::new(
                signal_frame::RootCode::new(0xff),
                signal_frame::VariantCode::new(0),
            ),
            FrameBody::HandshakeRequest(request),
        )
    }
    pub fn handshake_reply_frame(reply: signal_frame::HandshakeReply) -> Frame {
        Frame::new(
            signal_frame::WireRoute::new(
                signal_frame::RootCode::new(0xff),
                signal_frame::VariantCode::new(1),
            ),
            FrameBody::HandshakeReply(reply),
        )
    }
    pub fn decode_frame(bytes: &[u8]) -> Result<Frame, SignalFrameError> {
        if bytes.len() < signal_frame::SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: bytes.len(),
            });
        }
        let mut header_bytes = [0_u8; signal_frame::SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&bytes[..signal_frame::SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let contract_id = header as u32;
        let wire_revision = (header >> 32) as u16;
        if contract_id == 0 || wire_revision == 0 {
            return Err(SignalFrameError::LegacyHeader {
                contract_id,
                wire_revision,
            });
        }
        if contract_id != 1u32 {
            return Err(SignalFrameError::ContractMismatch {
                expected: 1u32,
                found: contract_id,
            });
        }
        if wire_revision != 1u16 {
            return Err(SignalFrameError::UnsupportedWireRevision {
                contract_id,
                expected: 1u16,
                found: wire_revision,
            });
        }
        let root = (header >> 56) as u8;
        let variant = (header >> 48) as u8;
        match (root, variant) {
            (0, 0) | (0, 1) | (1, 0) | (1, 1) | (0xff, 0) | (0xff, 1) | (0xff, 2) => {}
            _ => {
                return Err(SignalFrameError::UnknownRoute {
                    root,
                    variant,
                });
            }
        }
        if (root, variant) == (0xff, 2) {
            let refusal = rkyv::from_bytes::<
                EngineRefusal,
                rkyv::rancor::Error,
            >(&bytes[signal_frame::SHORT_HEADER_BYTE_COUNT..])
                .map_err(|_| SignalFrameError::ArchiveDecode)?;
            return Err(SignalFrameError::EngineRefused {
                refusal,
            });
        }
        let frame = Frame::decode(bytes).map_err(|_| SignalFrameError::ArchiveDecode)?;
        let header_route = signal_frame::WireRoute::new(
            signal_frame::RootCode::new(root),
            signal_frame::VariantCode::new(variant),
        );
        let body_matches = match frame.body() {
            FrameBody::HandshakeRequest(_) => (root, variant) == (0xff, 0),
            FrameBody::HandshakeReply(_) => (root, variant) == (0xff, 1),
            FrameBody::Request { request, .. } => {
                request.route().is_ok_and(|route| route == header_route)
            }
            FrameBody::Reply { reply, .. } => {
                match reply {
                    signal_frame::Reply::Accepted { per_operation, .. } => {
                        match per_operation.head() {
                            signal_frame::SubReply::Ok(output) => {
                                output.wire_route() == header_route
                            }
                            signal_frame::SubReply::Failed {
                                detail: Some(output),
                                ..
                            } => output.wire_route() == header_route,
                            signal_frame::SubReply::Invalidated
                            | signal_frame::SubReply::Failed { detail: None, .. }
                            | signal_frame::SubReply::Skipped => root == 1,
                        }
                    }
                    signal_frame::Reply::Rejected { .. } => root == 1,
                }
            }
        };
        if !body_matches {
            let body = match frame.body() {
                FrameBody::HandshakeRequest(_) => "handshake request",
                FrameBody::HandshakeReply(_) => "handshake reply",
                FrameBody::Request { .. } => "request",
                FrameBody::Reply { .. } => "reply",
            };
            return Err(SignalFrameError::RouteBodyMismatch {
                root,
                variant,
                body,
            });
        }
        Ok(frame)
    }
    pub fn decode_single_request(
        bytes: &[u8],
    ) -> Result<(signal_frame::ExchangeIdentifier, Input), SignalFrameError> {
        let frame = Self::decode_frame(bytes)?;
        match frame.into_body() {
            FrameBody::Request { exchange, request } => {
                let found = request.payloads().len();
                if found != 1 {
                    return Err(SignalFrameError::OperationCount {
                        found,
                    });
                }
                Ok((exchange, request.payloads.into_head()))
            }
            FrameBody::HandshakeRequest(_) => {
                Err(SignalFrameError::UnexpectedFrameBody {
                    found: "handshake request",
                })
            }
            FrameBody::HandshakeReply(_) => {
                Err(SignalFrameError::UnexpectedFrameBody {
                    found: "handshake reply",
                })
            }
            FrameBody::Reply { .. } => {
                Err(SignalFrameError::UnexpectedFrameBody {
                    found: "reply",
                })
            }
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Record,
    Observe,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    RecordAccepted,
    RecordsObserved,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Record(_) => InputRoute::Record,
            Self::Observe(_) => InputRoute::Observe,
        }
    }
    pub fn wire_route(&self) -> signal_frame::WireRoute {
        match self {
            Self::Record(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(0),
                )
            }
            Self::Observe(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(1),
                )
            }
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Record(_) => short_header::INPUT_RECORD,
            Self::Observe(_) => short_header::INPUT_OBSERVE,
        }
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::RecordAccepted(_) => OutputRoute::RecordAccepted,
            Self::RecordsObserved(_) => OutputRoute::RecordsObserved,
        }
    }
    pub fn wire_route(&self) -> signal_frame::WireRoute {
        match self {
            Self::RecordAccepted(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(0),
                )
            }
            Self::RecordsObserved(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(1),
                )
            }
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::RecordAccepted(_) => short_header::OUTPUT_RECORD_ACCEPTED,
            Self::RecordsObserved(_) => short_header::OUTPUT_RECORDS_OBSERVED,
        }
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &["Record", "Observe"];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        let route = self.wire_route();
        u64::from(route.root().value()) | (u64::from(route.variant().value()) << 8)
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::BoundExchangeFrame<ContractMarker, Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let route = self.wire_route();
        let request = signal_frame::Request::from_payload(self);
        Frame::new(
            route,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
    pub fn encode_request_frame(
        self,
        exchange: signal_frame::ExchangeIdentifier,
    ) -> Result<Vec<u8>, SignalFrameError> {
        self.into_frame(exchange).encode().map_err(|_| SignalFrameError::FrameEncode)
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let route = self.wire_route();
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::new(
            route,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
    pub fn encode_reply_frame(
        self,
        exchange: signal_frame::ExchangeIdentifier,
    ) -> Result<Vec<u8>, SignalFrameError> {
        self.into_reply_frame(exchange)
            .encode()
            .map_err(|_| SignalFrameError::FrameEncode)
    }
}
