// @generated by schema-rust
#[rustfmt::skip]
use thiserror::Error;
#[rustfmt::skip]
use triad_runtime::{
    AcceptedConnection, AsyncListenerError, AsyncConnectionRuntime,
    AsyncSingleListenerDaemon, AsyncSingleListenerDaemonError, ArgumentError,
    ComponentArgument, ComponentCommand, BindingSurface, ExitReport, RequestErrorLog,
};
#[rustfmt::skip]
use triad_runtime::EngineRequestError;
#[rustfmt::skip]
use triad_runtime::kameo::Actor;
#[rustfmt::skip]
use triad_runtime::kameo::actor::{ActorRef, Spawn, WeakActorRef};
#[rustfmt::skip]
use triad_runtime::kameo::error::{ActorStopReason, HookError, SendError};
#[rustfmt::skip]
use triad_runtime::kameo::message::{Context, Message};
#[rustfmt::skip]
use tokio::io::AsyncWriteExt;
#[rustfmt::skip]
use triad_runtime::{FrameBody, FrameError, LengthPrefixedCodec};
#[rustfmt::skip]
use crate::schema::signal::{
    ContractMarker, EngineRefusal, Input, Output, SignalFrameError,
};
#[rustfmt::skip]
/// The lane one decoded working `Input` runs on. `Immediate` is the
/// single-turn engine ask every component starts with; `Staged` runs
/// the three-phase staged turn — stage under the daemon's advance
/// gate, resolve on the connection task with no engine borrow, then
/// conclude in one more engine turn. Components without a staged
/// intake never return `Staged`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum WorkingInputLane {
    Immediate,
    Staged,
}
#[rustfmt::skip]
/// The component-facing stage verdict: the stage turn either
/// completed the input outright (a read, a refusal, a mode without
/// staging) or parked a staged advance awaiting external resolution.
pub enum StagedWorkingTurn<Daemon: ComponentDaemon> {
    Completed(Output),
    Awaiting(Box<dyn StagedAdvance<Daemon>>),
}
#[rustfmt::skip]
/// One staged advance crossing the daemon spine. `resolve` runs on
/// the connection task with NO engine borrow — the external wait
/// (for example a cluster authorization round) — storing its verdict
/// internally; `conclude` then runs as one fast engine turn and
/// produces the final `Output`.
pub trait StagedAdvance<Daemon: ComponentDaemon>: Send {
    fn resolve<'advance>(
        &'advance mut self,
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = ()> + Send + 'advance>>;
    fn conclude<'engine>(
        self: Box<Self>,
        engine: &'engine mut Daemon::Engine,
    ) -> std::pin::Pin<
        Box<
            dyn std::future::Future<
                Output = Result<Output, Daemon::Error>,
            > + Send + 'engine,
        >,
    >;
}
#[rustfmt::skip]
/// The component hook surface for the emitted daemon — the only daemon
/// code the component hand-writes (record 1488 escape hatches).
///
/// The component declares its `Configuration` / `Engine` / `Error` types
/// and `PROCESS_NAME`, and provides the REQUIRED `build_runtime` (the
/// emitter cannot know how to open the component's Store/Engine) plus the
/// typed working-input handler.
pub trait ComponentDaemon: Sized + 'static {
    type Configuration: BindingSurface;
    type ConfigurationError: std::error::Error;
    type Engine: Send + Sync + 'static;
    type Error: std::fmt::Debug
        + std::fmt::Display
        + From<FrameError>
        + From<SignalFrameError>
        + From<EngineRequestError>
        + Send
        + Sync
        + 'static;
    const PROCESS_NAME: &'static str;
    /// Load the binary rkyv `Configuration` from the daemon's single argument.
    fn load_configuration(
        path: &std::path::Path,
    ) -> Result<Self::Configuration, Self::ConfigurationError>;
    /// Validate the loaded configuration before any runtime, listener,
    /// or store is built. Components that carry only already-validated
    /// typed configuration keep the default no-op; components with decoded
    /// path records override this hook so bad startup shape fails before
    /// socket preparation or state mutation.
    fn validate_configuration(
        configuration: &Self::Configuration,
    ) -> Result<(), Self::ConfigurationError> {
        let _ = configuration;
        Ok(())
    }
    /// Open the component's durable Store and construct its Engine.
    fn build_runtime(
        configuration: &Self::Configuration,
    ) -> Result<Self::Engine, Self::Error>;
    /// Lifecycle: called once before the listener serves, once after it stops.
    fn start(engine: &Self::Engine) -> Result<(), Self::Error> {
        let _ = engine;
        Ok(())
    }
    fn stop(engine: &Self::Engine) -> Result<(), Self::Error> {
        let _ = engine;
        Ok(())
    }
    /// Run one decoded working `Input` through the engine and return the
    /// `Output` root to encode back to the caller.
    ///
    /// `connection` carries the accepted stream's kernel-vouched peer
    /// credentials (uid / gid / pid via `SO_PEERCRED`), so the component can
    /// mint an origin from the operating-system trust boundary rather than
    /// trusting a payload claim. Components that do not classify by origin
    /// take it as `_connection`.
    fn handle_working_input<'connection>(
        engine: &'connection mut Self::Engine,
        input: Input,
        connection: &'connection triad_runtime::ConnectionContext,
    ) -> impl std::future::Future<
        Output = Result<Output, Self::Error>,
    > + Send + 'connection;
    /// The lane a decoded working `Input` runs on. The default keeps
    /// every input on the single-turn `Immediate` ask, so components
    /// without a staged intake are unaffected.
    fn working_input_lane(input: &Input) -> WorkingInputLane {
        let _ = input;
        WorkingInputLane::Immediate
    }
    /// Stage one working `Input` — the fast first engine turn of the
    /// staged lane. The default completes immediately through
    /// `handle_working_input`, so a component that never returns
    /// `WorkingInputLane::Staged` never stages.
    fn stage_working_input<'connection>(
        engine: &'connection mut Self::Engine,
        input: Input,
        connection: &'connection triad_runtime::ConnectionContext,
    ) -> impl std::future::Future<
        Output = Result<StagedWorkingTurn<Self>, Self::Error>,
    > + Send + 'connection {
        async move {
            Ok(
                StagedWorkingTurn::Completed(
                    Self::handle_working_input(engine, input, connection).await?,
                ),
            )
        }
    }
    /// The component's shared advance gate, when it owns one: the
    /// daemon's staged lane serializes staged turns first-in first-out
    /// through this queue-fair lock, and a component can share the same
    /// gate with its own background passes. `None` lets the runtime own
    /// a private gate.
    fn shared_advance_gate(
        engine: &Self::Engine,
    ) -> Option<std::sync::Arc<tokio::sync::Mutex<()>>> {
        let _ = engine;
        None
    }
}
#[rustfmt::skip]
/// argv -> binary `Configuration` -> the bound daemon. The single-argument
/// rule: exactly one argument, a signal-encoded (rkyv) configuration file.
pub struct DaemonCommand<Daemon: ComponentDaemon> {
    command: ComponentCommand,
    daemon: std::marker::PhantomData<fn() -> Daemon>,
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> DaemonCommand<Daemon> {
    pub fn from_environment() -> Self {
        Self {
            command: ComponentCommand::from_environment(),
            daemon: std::marker::PhantomData,
        }
    }
    pub fn from_arguments<Arguments, Argument>(arguments: Arguments) -> Self
    where
        Arguments: IntoIterator<Item = Argument>,
        Argument: Into<String>,
    {
        Self {
            command: ComponentCommand::from_arguments(arguments),
            daemon: std::marker::PhantomData,
        }
    }
    pub fn configuration(&self) -> Result<Daemon::Configuration, DaemonError<Daemon>> {
        match self.command.signal_file_argument()? {
            ComponentArgument::SignalFile(file) => {
                let configuration = Daemon::load_configuration(file.as_path())
                    .map_err(DaemonError::Configuration)?;
                Daemon::validate_configuration(&configuration)
                    .map_err(DaemonError::Configuration)?;
                Ok(configuration)
            }
            ComponentArgument::InlineNota(_) | ComponentArgument::NotaFile(_) => {
                Err(DaemonError::Argument(ArgumentError::ExpectedSignalFile))
            }
        }
    }
    pub fn run(&self) -> Result<(), DaemonError<Daemon>> {
        tokio::runtime::Runtime::new()
            .map_err(DaemonError::Runtime)?
            .block_on(async {
                Daemon::bind(self.configuration()?)?
                    .run()
                    .await
                    .map_err(DaemonError::from)
            })
    }
}
#[rustfmt::skip]
/// The bound daemon constructor on the component trait: builds the engine,
/// wraps it in the generated actor connection runtime, and returns the
/// async task-backed listener shell the `DaemonCommand` drives. The component
/// never writes this by hand — it is emitted as a default method on
/// `ComponentDaemon`.
pub trait DaemonBinder: ComponentDaemon {
    fn bind(
        configuration: Self::Configuration,
    ) -> Result<
        AsyncSingleListenerDaemon<GeneratedDaemonRuntime<Self>>,
        DaemonError<Self>,
    > {
        let engine = Self::build_runtime(&configuration)
            .map_err(DaemonError::Component)?;
        let runtime = GeneratedDaemonRuntime::<Self>::new(engine);
        Ok({
            let daemon = AsyncSingleListenerDaemon::new(
                    configuration.socket_path().to_path_buf(),
                    runtime.clone(),
                    RequestErrorLog::new(Self::PROCESS_NAME),
                )
                .with_concurrency_limit(configuration.request_concurrency_limit());
            match configuration.socket_mode() {
                Some(socket_mode) => daemon.with_socket_mode(socket_mode),
                None => daemon,
            }
        })
    }
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> DaemonBinder for Daemon {}
#[rustfmt::skip]
/// The working-tier wire transport over one accepted stream: a
/// length-prefixed envelope around the schema-emitted signal frame codec.
struct WorkingTransport<'connection, Stream> {
    connection: &'connection mut AcceptedConnection<Stream>,
}
#[rustfmt::skip]
impl<'connection, Stream> WorkingTransport<'connection, Stream>
where
    Stream: tokio::io::AsyncRead + tokio::io::AsyncWrite + Unpin,
{
    fn new(connection: &'connection mut AcceptedConnection<Stream>) -> Self {
        Self { connection }
    }
    fn context(&self) -> &triad_runtime::ConnectionContext {
        self.connection.context()
    }
    async fn read_frame(&mut self) -> Result<Vec<u8>, FrameError> {
        Ok(
            LengthPrefixedCodec::default()
                .read_body_async(self.connection.stream_mut())
                .await?
                .into_bytes(),
        )
    }
    async fn write_frame(&mut self, frame: Vec<u8>) -> Result<(), FrameError> {
        LengthPrefixedCodec::default()
            .write_body_async(self.connection.stream_mut(), &FrameBody::new(frame))
            .await?;
        self.connection.stream_mut().flush().await?;
        Ok(())
    }
}
#[rustfmt::skip]
/// The kameo actor that owns the component engine. The mailbox
/// serialises every request, giving each handler exclusive `&mut`
/// access to the engine without a component-internal lock.
pub struct EngineActor<Daemon: ComponentDaemon> {
    engine: Daemon::Engine,
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> Actor for EngineActor<Daemon> {
    type Args = Self;
    type Error = Daemon::Error;
    async fn on_start(
        actor: Self::Args,
        _actor_reference: ActorRef<Self>,
    ) -> Result<Self, Self::Error> {
        Daemon::start(&actor.engine)?;
        Ok(actor)
    }
    async fn on_stop(
        &mut self,
        _actor_reference: WeakActorRef<Self>,
        _reason: ActorStopReason,
    ) -> Result<(), Self::Error> {
        Daemon::stop(&self.engine)
    }
}
#[rustfmt::skip]
#[derive(Debug)]
pub struct WorkingInput {
    input: Input,
    context: triad_runtime::ConnectionContext,
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> Message<WorkingInput> for EngineActor<Daemon> {
    type Reply = Result<Output, Daemon::Error>;
    async fn handle(
        &mut self,
        message: WorkingInput,
        _context: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        Daemon::handle_working_input(&mut self.engine, message.input, &message.context)
            .await
    }
}
#[rustfmt::skip]
/// The engine actor's stage reply: `Completed` carries the finished
/// outcome; `Awaiting` carries the staged advance the connection task
/// resolves before the concluding engine turn.
pub enum StagedWorkingReply<Daemon: ComponentDaemon> {
    Completed(Output),
    Awaiting(Box<dyn StagedAdvance<Daemon>>),
}
#[rustfmt::skip]
pub struct StageWorkingInput {
    input: Input,
    context: triad_runtime::ConnectionContext,
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> Message<StageWorkingInput> for EngineActor<Daemon> {
    type Reply = Result<StagedWorkingReply<Daemon>, Daemon::Error>;
    async fn handle(
        &mut self,
        message: StageWorkingInput,
        _context: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        match Daemon::stage_working_input(
                &mut self.engine,
                message.input,
                &message.context,
            )
            .await?
        {
            StagedWorkingTurn::Completed(output) => {
                Ok(StagedWorkingReply::Completed(output))
            }
            StagedWorkingTurn::Awaiting(advance) => {
                Ok(StagedWorkingReply::Awaiting(advance))
            }
        }
    }
}
#[rustfmt::skip]
pub struct ConcludeWorkingInput<Daemon: ComponentDaemon> {
    advance: Box<dyn StagedAdvance<Daemon>>,
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> Message<ConcludeWorkingInput<Daemon>>
for EngineActor<Daemon> {
    type Reply = Result<Output, Daemon::Error>;
    async fn handle(
        &mut self,
        message: ConcludeWorkingInput<Daemon>,
        _context: &mut Context<Self, Self::Reply>,
    ) -> Self::Reply {
        message.advance.conclude(&mut self.engine).await
    }
}
#[rustfmt::skip]
/// One refused working turn: the component's typed error for the
/// daemon-side log plus the wire refusal written to the caller.
struct RefusedWorkingTurn<DaemonError> {
    error: DaemonError,
    refusal: EngineRefusal,
}
#[rustfmt::skip]
/// The generated runtime struct holds an `ActorRef` to the engine
/// actor. Its `handle_connection` IS the async decode -> ask -> encode
/// spine; the engine state lives behind the actor mailbox. The advance
/// gate serializes staged working turns first-in first-out across
/// their stage, resolve, and conclude phases.
pub struct GeneratedDaemonRuntime<Daemon: ComponentDaemon> {
    engine: ActorRef<EngineActor<Daemon>>,
    advance_gate: std::sync::Arc<tokio::sync::Mutex<()>>,
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> GeneratedDaemonRuntime<Daemon> {
    fn new(engine: Daemon::Engine) -> Self {
        let advance_gate = Daemon::shared_advance_gate(&engine).unwrap_or_default();
        Self {
            engine: EngineActor::<Daemon>::spawn(EngineActor { engine }),
            advance_gate,
        }
    }
    /// Translate a kameo `SendError` from an engine `ask` into the
    /// refused turn the spine answers with: the component's typed
    /// `Error` for the daemon side, plus the wire refusal the
    /// caller receives. A handler error is the engine rejecting
    /// the request; every mailbox-layer failure is the engine
    /// being unavailable.
    fn engine_ask_refused<Request>(
        error: SendError<Request, Daemon::Error>,
    ) -> RefusedWorkingTurn<Daemon::Error> {
        match error {
            SendError::HandlerError(error) => {
                let refusal = EngineRefusal::rejected(error.to_string());
                RefusedWorkingTurn {
                    error,
                    refusal,
                }
            }
            SendError::ActorNotRunning(_) => {
                Self::engine_unavailable("engine actor is not running")
            }
            SendError::ActorStopped => {
                Self::engine_unavailable("engine actor stopped before replying")
            }
            SendError::MailboxFull(_) => {
                Self::engine_unavailable("engine actor mailbox is full")
            }
            SendError::Timeout(_) => {
                Self::engine_unavailable("engine actor request timed out")
            }
        }
    }
    fn engine_unavailable(detail: &str) -> RefusedWorkingTurn<Daemon::Error> {
        RefusedWorkingTurn {
            error: EngineRequestError::new(detail).into(),
            refusal: EngineRefusal::unavailable(detail.to_string()),
        }
    }
    /// Best-effort refusal write: the engine failure outranks any
    /// secondary transport failure, which the caller experiences
    /// as the closed exchange it already handles today.
    async fn write_refusal_frame<Stream>(
        transport: &mut WorkingTransport<'_, Stream>,
        refusal: EngineRefusal,
    )
    where
        Stream: tokio::io::AsyncRead + tokio::io::AsyncWrite + Unpin,
    {
        if let Ok(frame) = refusal.encode_bound_frame() {
            let _ = transport.write_frame(frame).await;
        }
    }
    async fn handle_working_connection<Stream>(
        &self,
        mut connection: AcceptedConnection<Stream>,
    ) -> Result<(), Daemon::Error>
    where
        Stream: tokio::io::AsyncRead + tokio::io::AsyncWrite + Unpin,
    {
        let mut transport = WorkingTransport::new(&mut connection);
        let frame = transport.read_frame().await?;
        let (exchange, input) = ContractMarker::decode_single_request(&frame)?;
        let context = *transport.context();
        let turn = match Daemon::working_input_lane(&input) {
            WorkingInputLane::Immediate => {
                match self.engine.ask(WorkingInput { input, context }).await {
                    Ok(output) => Ok(output),
                    Err(error) => Err(Self::engine_ask_refused(error)),
                }
            }
            WorkingInputLane::Staged => {
                let _advance_turn = self.advance_gate.lock().await;
                match self
                    .engine
                    .ask(StageWorkingInput {
                        input,
                        context,
                    })
                    .await
                {
                    Ok(StagedWorkingReply::Completed(output)) => Ok(output),
                    Ok(StagedWorkingReply::Awaiting(mut advance)) => {
                        advance.resolve().await;
                        match self.engine.ask(ConcludeWorkingInput { advance }).await {
                            Ok(output) => Ok(output),
                            Err(error) => Err(Self::engine_ask_refused(error)),
                        }
                    }
                    Err(error) => Err(Self::engine_ask_refused(error)),
                }
            }
        };
        match turn {
            Ok(output) => {
                match output.encode_reply_frame(exchange) {
                    Ok(reply) => {
                        transport.write_frame(reply).await?;
                        Ok(())
                    }
                    Err(error) => {
                        let refusal = EngineRefusal::unavailable(error.to_string());
                        Self::write_refusal_frame(&mut transport, refusal).await;
                        Err(error.into())
                    }
                }
            }
            Err(refused) => {
                Self::write_refusal_frame(&mut transport, refused.refusal).await;
                Err(refused.error)
            }
        }
    }
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> Clone for GeneratedDaemonRuntime<Daemon> {
    fn clone(&self) -> Self {
        Self {
            engine: self.engine.clone(),
            advance_gate: self.advance_gate.clone(),
        }
    }
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> AsyncConnectionRuntime for GeneratedDaemonRuntime<Daemon> {
    type Error = Daemon::Error;
    async fn start(&self) -> Result<(), Daemon::Error> {
        self.engine
            .wait_for_startup_with_result(|result| match result {
                Ok(()) => Ok(()),
                Err(HookError::Error(error)) => {
                    Err(
                        EngineRequestError::new(
                                format!("engine actor failed to start: {error:?}"),
                            )
                            .into(),
                    )
                }
                Err(HookError::Panicked(_)) => {
                    Err(
                        EngineRequestError::new("engine actor panicked during startup")
                            .into(),
                    )
                }
            })
            .await
    }
    async fn stop(&self) -> Result<(), Daemon::Error> {
        let _ = self.engine.stop_gracefully().await;
        self.engine.wait_for_shutdown().await;
        Ok(())
    }
    async fn handle_connection(
        &self,
        connection: AcceptedConnection,
    ) -> Result<(), Self::Error> {
        self.handle_working_connection(connection).await
    }
}
#[rustfmt::skip]
/// The emitted daemon error: argv, configuration, listener, and the
/// component error. The component's own error rides the `Component` arm.
#[derive(Debug, Error)]
pub enum DaemonError<Daemon: ComponentDaemon> {
    #[error("daemon argument error: {0}")]
    Argument(ArgumentError),
    #[error("daemon configuration error: {0}")]
    Configuration(Daemon::ConfigurationError),
    #[error("daemon runtime error: {0}")]
    Runtime(std::io::Error),
    #[error("daemon listener error: {0}")]
    Listener(AsyncListenerError),
    #[error("component error: {0}")]
    Component(Daemon::Error),
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> From<ArgumentError> for DaemonError<Daemon> {
    fn from(error: ArgumentError) -> Self {
        Self::Argument(error)
    }
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> From<AsyncSingleListenerDaemonError<Daemon::Error>>
for DaemonError<Daemon> {
    fn from(error: AsyncSingleListenerDaemonError<Daemon::Error>) -> Self {
        match error {
            AsyncSingleListenerDaemonError::Listener(error) => Self::Listener(error),
            AsyncSingleListenerDaemonError::Start(error)
            | AsyncSingleListenerDaemonError::Stop(error) => Self::Component(error),
        }
    }
}
#[rustfmt::skip]
/// The component-agnostic exit body. The component's binary calls
/// `<SpiritDaemon as DaemonEntry>::run_to_exit_code()` from `fn main`.
pub trait DaemonEntry: ComponentDaemon {
    fn run_to_exit_code() -> std::process::ExitCode {
        ExitReport::new(Self::PROCESS_NAME)
            .from_result(DaemonCommand::<Self>::from_environment().run())
    }
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> DaemonEntry for Daemon {}
