// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use reaction::schema::reaction::Work as Work;
#[rustfmt::skip]
pub use reaction::schema::reaction::Action as Action;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignalInput(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignalOutput(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaReadInput(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaReadOutput(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaWriteOutput(Boolean);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Records(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordCount(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StashHandle(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DatabaseMarker {
    pub commit_sequence: Integer,
    pub state_digest: Integer,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Statement(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordRequest(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Proposal(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Entry(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Clarification(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Supersession(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Retirement(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaReceipt {
    pub record_identifier: RecordIdentifier,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ClarificationReceipt(Boolean);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SupersessionReceipt(Boolean);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetirementReceipt(Boolean);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RemoveReceipt(Boolean);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordChangeReceipt(Boolean);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GuardianRejection {
    pub guardian_rejection_reason: GuardianRejectionReason,
    pub explanation: Explanation,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GuardianRejectionReason(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReferentGuardianRejection {
    pub referent_guardian_rejection_reason: ReferentGuardianRejectionReason,
    pub explanation: Explanation,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReferentGuardianRejectionReason(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Explanation(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ErrorReport(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Query(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubscriptionToken(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IntentSubscription(SubscriptionToken);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Removal(RecordIdentifier);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CertaintyChange(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ImportanceBump(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordChange(RecordIdentifier);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReferentRegistration(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReferentRegistrationReceipt(Boolean);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RemovalCandidateCollection(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RemovalCandidatesCollection(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObserverFilter(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObserverSubscription(SubscriptionToken);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObserverRetraction(SubscriptionToken);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaWriteSet {
    Record(Entry),
    Remove(Removal),
    ChangeCertainty(CertaintyChange),
    BumpImportance(ImportanceBump),
    ChangeRecord(RecordChange),
    RegisterReferent(ReferentRegistration),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Record(Entry);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Remove(Removal);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChangeCertainty(CertaintyChange);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct BumpImportance(ImportanceBump);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChangeRecord(RecordChange);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RegisterReferent(ReferentRegistration);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum EffectCommand {
    Stash(StashRequest),
    ClassifyState(Statement),
    RecordWithImpliedReferents(RecordRequest),
    GuardRecord(RecordRequest),
    ProposeWithImpliedReferents(Proposal),
    Propose(Proposal),
    Clarify(Clarification),
    SupersedeWithImpliedReferents(Supersession),
    Supersede(Supersession),
    Retire(Retirement),
    GuardRemove(Removal),
    ChangeRecordWithImpliedReferents(RecordChange),
    GuardChangeRecord(RecordChange),
    GuardReferentRegistration(ReferentRegistration),
    OpenIntentSubscription(Query),
    CollectRemovalCandidates(RemovalCandidateCollection),
    OpenObserverTap(ObserverFilter),
    CloseObserverTap(SubscriptionToken),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Stash(StashRequest);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ClassifyState(Statement);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordWithImpliedReferents(RecordRequest);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GuardRecord(RecordRequest);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProposeWithImpliedReferents(Proposal);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Propose(Proposal);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Clarify(Clarification);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SupersedeWithImpliedReferents(Supersession);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Supersede(Supersession);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Retire(Retirement);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GuardRemove(Removal);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChangeRecordWithImpliedReferents(RecordChange);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GuardChangeRecord(RecordChange);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GuardReferentRegistration(ReferentRegistration);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OpenIntentSubscription(Query);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CollectRemovalCandidates(RemovalCandidateCollection);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OpenObserverTap(ObserverFilter);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CloseObserverTap(SubscriptionToken);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum EffectOutcome {
    Stashed(StashResult),
    StateClassified(RecordRequest),
    RecordReferentsSettled(RecordRequest),
    ProposeReferentsSettled(Proposal),
    SupersedeReferentsSettled(Supersession),
    ChangeRecordReferentsSettled(RecordChange),
    Recorded(SemaReceipt),
    Proposed(SemaReceipt),
    Clarified(ClarificationReceipt),
    Superseded(SupersessionReceipt),
    Retired(RetirementReceipt),
    Removed(RemoveReceipt),
    RecordChanged(RecordChangeReceipt),
    GuardianRejected(GuardianRejection),
    ReferentRegistered(ReferentRegistrationReceipt),
    ReferentGuardianRejected(ReferentGuardianRejection),
    OperationFailed(ErrorReport),
    IntentSubscriptionOpened(IntentSubscription),
    RemovalCandidatesCollected(RemovalCandidatesCollection),
    ObserverTapOpened(ObserverSubscription),
    ObserverTapClosed(ObserverRetraction),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Stashed(StashResult);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StateClassified(RecordRequest);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordReferentsSettled(RecordRequest);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProposeReferentsSettled(Proposal);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SupersedeReferentsSettled(Supersession);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChangeRecordReferentsSettled(RecordChange);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Recorded(SemaReceipt);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Proposed(SemaReceipt);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Clarified(ClarificationReceipt);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Superseded(SupersessionReceipt);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Retired(RetirementReceipt);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Removed(RemoveReceipt);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordChanged(RecordChangeReceipt);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GuardianRejected(GuardianRejection);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReferentRegistered(ReferentRegistrationReceipt);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReferentGuardianRejected(ReferentGuardianRejection);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OperationFailed(ErrorReport);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IntentSubscriptionOpened(IntentSubscription);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RemovalCandidatesCollected(RemovalCandidatesCollection);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObserverTapOpened(ObserverSubscription);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObserverTapClosed(ObserverRetraction);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StashRequest {
    pub records: Records,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StashResult {
    pub stash_handle: StashHandle,
    pub record_count: RecordCount,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    SignalArrived(SignalInput),
    SemaWriteCompleted(SemaWriteOutput),
    SemaReadCompleted(SemaReadOutput),
    EffectCompleted(EffectOutcome),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    ReplyToSignal(SignalOutput),
    CommandSemaWrite(SemaWriteSet),
    CommandSemaRead(SemaReadInput),
    CommandEffect(EffectCommand),
    Continue(Input),
}

#[rustfmt::skip]
impl SignalInput {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for SignalInput {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SignalOutput {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for SignalOutput {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaReadInput {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for SemaReadInput {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaReadOutput {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for SemaReadOutput {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaWriteOutput {
    pub fn new(payload: Boolean) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Boolean {
        &self.0
    }
    pub fn into_payload(self) -> Boolean {
        self.0
    }
}
#[rustfmt::skip]
impl From<Boolean> for SemaWriteOutput {
    fn from(payload: Boolean) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Records {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for Records {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RecordCount {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for RecordCount {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StashHandle {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for StashHandle {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Statement {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Statement {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RecordRequest {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for RecordRequest {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Proposal {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Proposal {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Entry {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Entry {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Clarification {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Clarification {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Supersession {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Supersession {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Retirement {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Retirement {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ClarificationReceipt {
    pub fn new(payload: Boolean) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Boolean {
        &self.0
    }
    pub fn into_payload(self) -> Boolean {
        self.0
    }
}
#[rustfmt::skip]
impl From<Boolean> for ClarificationReceipt {
    fn from(payload: Boolean) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SupersessionReceipt {
    pub fn new(payload: Boolean) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Boolean {
        &self.0
    }
    pub fn into_payload(self) -> Boolean {
        self.0
    }
}
#[rustfmt::skip]
impl From<Boolean> for SupersessionReceipt {
    fn from(payload: Boolean) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RetirementReceipt {
    pub fn new(payload: Boolean) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Boolean {
        &self.0
    }
    pub fn into_payload(self) -> Boolean {
        self.0
    }
}
#[rustfmt::skip]
impl From<Boolean> for RetirementReceipt {
    fn from(payload: Boolean) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RemoveReceipt {
    pub fn new(payload: Boolean) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Boolean {
        &self.0
    }
    pub fn into_payload(self) -> Boolean {
        self.0
    }
}
#[rustfmt::skip]
impl From<Boolean> for RemoveReceipt {
    fn from(payload: Boolean) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RecordChangeReceipt {
    pub fn new(payload: Boolean) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Boolean {
        &self.0
    }
    pub fn into_payload(self) -> Boolean {
        self.0
    }
}
#[rustfmt::skip]
impl From<Boolean> for RecordChangeReceipt {
    fn from(payload: Boolean) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GuardianRejectionReason {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for GuardianRejectionReason {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ReferentGuardianRejectionReason {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ReferentGuardianRejectionReason {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Explanation {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Explanation {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ErrorReport {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ErrorReport {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Query {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Query {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SubscriptionToken {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for SubscriptionToken {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl IntentSubscription {
    pub fn new(payload: SubscriptionToken) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SubscriptionToken {
        &self.0
    }
    pub fn into_payload(self) -> SubscriptionToken {
        self.0
    }
}
#[rustfmt::skip]
impl From<SubscriptionToken> for IntentSubscription {
    fn from(payload: SubscriptionToken) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RecordIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for RecordIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Removal {
    pub fn new(payload: RecordIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RecordIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> RecordIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<RecordIdentifier> for Removal {
    fn from(payload: RecordIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CertaintyChange {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for CertaintyChange {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ImportanceBump {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for ImportanceBump {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RecordChange {
    pub fn new(payload: RecordIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RecordIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> RecordIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<RecordIdentifier> for RecordChange {
    fn from(payload: RecordIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ReferentRegistration {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ReferentRegistration {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ReferentRegistrationReceipt {
    pub fn new(payload: Boolean) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Boolean {
        &self.0
    }
    pub fn into_payload(self) -> Boolean {
        self.0
    }
}
#[rustfmt::skip]
impl From<Boolean> for ReferentRegistrationReceipt {
    fn from(payload: Boolean) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RemovalCandidateCollection {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for RemovalCandidateCollection {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RemovalCandidatesCollection {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for RemovalCandidatesCollection {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ObserverFilter {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ObserverFilter {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ObserverSubscription {
    pub fn new(payload: SubscriptionToken) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SubscriptionToken {
        &self.0
    }
    pub fn into_payload(self) -> SubscriptionToken {
        self.0
    }
}
#[rustfmt::skip]
impl From<SubscriptionToken> for ObserverSubscription {
    fn from(payload: SubscriptionToken) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ObserverRetraction {
    pub fn new(payload: SubscriptionToken) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SubscriptionToken {
        &self.0
    }
    pub fn into_payload(self) -> SubscriptionToken {
        self.0
    }
}
#[rustfmt::skip]
impl From<SubscriptionToken> for ObserverRetraction {
    fn from(payload: SubscriptionToken) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Record {
    pub fn new(payload: Entry) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Entry {
        &self.0
    }
    pub fn into_payload(self) -> Entry {
        self.0
    }
}
#[rustfmt::skip]
impl From<Entry> for Record {
    fn from(payload: Entry) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Remove {
    pub fn new(payload: Removal) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Removal {
        &self.0
    }
    pub fn into_payload(self) -> Removal {
        self.0
    }
}
#[rustfmt::skip]
impl From<Removal> for Remove {
    fn from(payload: Removal) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ChangeCertainty {
    pub fn new(payload: CertaintyChange) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CertaintyChange {
        &self.0
    }
    pub fn into_payload(self) -> CertaintyChange {
        self.0
    }
}
#[rustfmt::skip]
impl From<CertaintyChange> for ChangeCertainty {
    fn from(payload: CertaintyChange) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl BumpImportance {
    pub fn new(payload: ImportanceBump) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ImportanceBump {
        &self.0
    }
    pub fn into_payload(self) -> ImportanceBump {
        self.0
    }
}
#[rustfmt::skip]
impl From<ImportanceBump> for BumpImportance {
    fn from(payload: ImportanceBump) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ChangeRecord {
    pub fn new(payload: RecordChange) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RecordChange {
        &self.0
    }
    pub fn into_payload(self) -> RecordChange {
        self.0
    }
}
#[rustfmt::skip]
impl From<RecordChange> for ChangeRecord {
    fn from(payload: RecordChange) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RegisterReferent {
    pub fn new(payload: ReferentRegistration) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ReferentRegistration {
        &self.0
    }
    pub fn into_payload(self) -> ReferentRegistration {
        self.0
    }
}
#[rustfmt::skip]
impl From<ReferentRegistration> for RegisterReferent {
    fn from(payload: ReferentRegistration) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Stash {
    pub fn new(payload: StashRequest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StashRequest {
        &self.0
    }
    pub fn into_payload(self) -> StashRequest {
        self.0
    }
}
#[rustfmt::skip]
impl From<StashRequest> for Stash {
    fn from(payload: StashRequest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ClassifyState {
    pub fn new(payload: Statement) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Statement {
        &self.0
    }
    pub fn into_payload(self) -> Statement {
        self.0
    }
}
#[rustfmt::skip]
impl From<Statement> for ClassifyState {
    fn from(payload: Statement) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RecordWithImpliedReferents {
    pub fn new(payload: RecordRequest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RecordRequest {
        &self.0
    }
    pub fn into_payload(self) -> RecordRequest {
        self.0
    }
}
#[rustfmt::skip]
impl From<RecordRequest> for RecordWithImpliedReferents {
    fn from(payload: RecordRequest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GuardRecord {
    pub fn new(payload: RecordRequest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RecordRequest {
        &self.0
    }
    pub fn into_payload(self) -> RecordRequest {
        self.0
    }
}
#[rustfmt::skip]
impl From<RecordRequest> for GuardRecord {
    fn from(payload: RecordRequest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ProposeWithImpliedReferents {
    pub fn new(payload: Proposal) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Proposal {
        &self.0
    }
    pub fn into_payload(self) -> Proposal {
        self.0
    }
}
#[rustfmt::skip]
impl From<Proposal> for ProposeWithImpliedReferents {
    fn from(payload: Proposal) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Propose {
    pub fn new(payload: Proposal) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Proposal {
        &self.0
    }
    pub fn into_payload(self) -> Proposal {
        self.0
    }
}
#[rustfmt::skip]
impl From<Proposal> for Propose {
    fn from(payload: Proposal) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Clarify {
    pub fn new(payload: Clarification) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Clarification {
        &self.0
    }
    pub fn into_payload(self) -> Clarification {
        self.0
    }
}
#[rustfmt::skip]
impl From<Clarification> for Clarify {
    fn from(payload: Clarification) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SupersedeWithImpliedReferents {
    pub fn new(payload: Supersession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Supersession {
        &self.0
    }
    pub fn into_payload(self) -> Supersession {
        self.0
    }
}
#[rustfmt::skip]
impl From<Supersession> for SupersedeWithImpliedReferents {
    fn from(payload: Supersession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Supersede {
    pub fn new(payload: Supersession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Supersession {
        &self.0
    }
    pub fn into_payload(self) -> Supersession {
        self.0
    }
}
#[rustfmt::skip]
impl From<Supersession> for Supersede {
    fn from(payload: Supersession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Retire {
    pub fn new(payload: Retirement) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Retirement {
        &self.0
    }
    pub fn into_payload(self) -> Retirement {
        self.0
    }
}
#[rustfmt::skip]
impl From<Retirement> for Retire {
    fn from(payload: Retirement) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GuardRemove {
    pub fn new(payload: Removal) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Removal {
        &self.0
    }
    pub fn into_payload(self) -> Removal {
        self.0
    }
}
#[rustfmt::skip]
impl From<Removal> for GuardRemove {
    fn from(payload: Removal) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ChangeRecordWithImpliedReferents {
    pub fn new(payload: RecordChange) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RecordChange {
        &self.0
    }
    pub fn into_payload(self) -> RecordChange {
        self.0
    }
}
#[rustfmt::skip]
impl From<RecordChange> for ChangeRecordWithImpliedReferents {
    fn from(payload: RecordChange) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GuardChangeRecord {
    pub fn new(payload: RecordChange) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RecordChange {
        &self.0
    }
    pub fn into_payload(self) -> RecordChange {
        self.0
    }
}
#[rustfmt::skip]
impl From<RecordChange> for GuardChangeRecord {
    fn from(payload: RecordChange) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GuardReferentRegistration {
    pub fn new(payload: ReferentRegistration) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ReferentRegistration {
        &self.0
    }
    pub fn into_payload(self) -> ReferentRegistration {
        self.0
    }
}
#[rustfmt::skip]
impl From<ReferentRegistration> for GuardReferentRegistration {
    fn from(payload: ReferentRegistration) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl OpenIntentSubscription {
    pub fn new(payload: Query) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Query {
        &self.0
    }
    pub fn into_payload(self) -> Query {
        self.0
    }
}
#[rustfmt::skip]
impl From<Query> for OpenIntentSubscription {
    fn from(payload: Query) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CollectRemovalCandidates {
    pub fn new(payload: RemovalCandidateCollection) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RemovalCandidateCollection {
        &self.0
    }
    pub fn into_payload(self) -> RemovalCandidateCollection {
        self.0
    }
}
#[rustfmt::skip]
impl From<RemovalCandidateCollection> for CollectRemovalCandidates {
    fn from(payload: RemovalCandidateCollection) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl OpenObserverTap {
    pub fn new(payload: ObserverFilter) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ObserverFilter {
        &self.0
    }
    pub fn into_payload(self) -> ObserverFilter {
        self.0
    }
}
#[rustfmt::skip]
impl From<ObserverFilter> for OpenObserverTap {
    fn from(payload: ObserverFilter) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CloseObserverTap {
    pub fn new(payload: SubscriptionToken) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SubscriptionToken {
        &self.0
    }
    pub fn into_payload(self) -> SubscriptionToken {
        self.0
    }
}
#[rustfmt::skip]
impl From<SubscriptionToken> for CloseObserverTap {
    fn from(payload: SubscriptionToken) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Stashed {
    pub fn new(payload: StashResult) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StashResult {
        &self.0
    }
    pub fn into_payload(self) -> StashResult {
        self.0
    }
}
#[rustfmt::skip]
impl From<StashResult> for Stashed {
    fn from(payload: StashResult) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StateClassified {
    pub fn new(payload: RecordRequest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RecordRequest {
        &self.0
    }
    pub fn into_payload(self) -> RecordRequest {
        self.0
    }
}
#[rustfmt::skip]
impl From<RecordRequest> for StateClassified {
    fn from(payload: RecordRequest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RecordReferentsSettled {
    pub fn new(payload: RecordRequest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RecordRequest {
        &self.0
    }
    pub fn into_payload(self) -> RecordRequest {
        self.0
    }
}
#[rustfmt::skip]
impl From<RecordRequest> for RecordReferentsSettled {
    fn from(payload: RecordRequest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ProposeReferentsSettled {
    pub fn new(payload: Proposal) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Proposal {
        &self.0
    }
    pub fn into_payload(self) -> Proposal {
        self.0
    }
}
#[rustfmt::skip]
impl From<Proposal> for ProposeReferentsSettled {
    fn from(payload: Proposal) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SupersedeReferentsSettled {
    pub fn new(payload: Supersession) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Supersession {
        &self.0
    }
    pub fn into_payload(self) -> Supersession {
        self.0
    }
}
#[rustfmt::skip]
impl From<Supersession> for SupersedeReferentsSettled {
    fn from(payload: Supersession) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ChangeRecordReferentsSettled {
    pub fn new(payload: RecordChange) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RecordChange {
        &self.0
    }
    pub fn into_payload(self) -> RecordChange {
        self.0
    }
}
#[rustfmt::skip]
impl From<RecordChange> for ChangeRecordReferentsSettled {
    fn from(payload: RecordChange) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Recorded {
    pub fn new(payload: SemaReceipt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaReceipt {
        &self.0
    }
    pub fn into_payload(self) -> SemaReceipt {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaReceipt> for Recorded {
    fn from(payload: SemaReceipt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Proposed {
    pub fn new(payload: SemaReceipt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaReceipt {
        &self.0
    }
    pub fn into_payload(self) -> SemaReceipt {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaReceipt> for Proposed {
    fn from(payload: SemaReceipt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Clarified {
    pub fn new(payload: ClarificationReceipt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ClarificationReceipt {
        &self.0
    }
    pub fn into_payload(self) -> ClarificationReceipt {
        self.0
    }
}
#[rustfmt::skip]
impl From<ClarificationReceipt> for Clarified {
    fn from(payload: ClarificationReceipt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Superseded {
    pub fn new(payload: SupersessionReceipt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SupersessionReceipt {
        &self.0
    }
    pub fn into_payload(self) -> SupersessionReceipt {
        self.0
    }
}
#[rustfmt::skip]
impl From<SupersessionReceipt> for Superseded {
    fn from(payload: SupersessionReceipt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Retired {
    pub fn new(payload: RetirementReceipt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RetirementReceipt {
        &self.0
    }
    pub fn into_payload(self) -> RetirementReceipt {
        self.0
    }
}
#[rustfmt::skip]
impl From<RetirementReceipt> for Retired {
    fn from(payload: RetirementReceipt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Removed {
    pub fn new(payload: RemoveReceipt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RemoveReceipt {
        &self.0
    }
    pub fn into_payload(self) -> RemoveReceipt {
        self.0
    }
}
#[rustfmt::skip]
impl From<RemoveReceipt> for Removed {
    fn from(payload: RemoveReceipt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RecordChanged {
    pub fn new(payload: RecordChangeReceipt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RecordChangeReceipt {
        &self.0
    }
    pub fn into_payload(self) -> RecordChangeReceipt {
        self.0
    }
}
#[rustfmt::skip]
impl From<RecordChangeReceipt> for RecordChanged {
    fn from(payload: RecordChangeReceipt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GuardianRejected {
    pub fn new(payload: GuardianRejection) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &GuardianRejection {
        &self.0
    }
    pub fn into_payload(self) -> GuardianRejection {
        self.0
    }
}
#[rustfmt::skip]
impl From<GuardianRejection> for GuardianRejected {
    fn from(payload: GuardianRejection) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ReferentRegistered {
    pub fn new(payload: ReferentRegistrationReceipt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ReferentRegistrationReceipt {
        &self.0
    }
    pub fn into_payload(self) -> ReferentRegistrationReceipt {
        self.0
    }
}
#[rustfmt::skip]
impl From<ReferentRegistrationReceipt> for ReferentRegistered {
    fn from(payload: ReferentRegistrationReceipt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ReferentGuardianRejected {
    pub fn new(payload: ReferentGuardianRejection) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ReferentGuardianRejection {
        &self.0
    }
    pub fn into_payload(self) -> ReferentGuardianRejection {
        self.0
    }
}
#[rustfmt::skip]
impl From<ReferentGuardianRejection> for ReferentGuardianRejected {
    fn from(payload: ReferentGuardianRejection) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl OperationFailed {
    pub fn new(payload: ErrorReport) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ErrorReport {
        &self.0
    }
    pub fn into_payload(self) -> ErrorReport {
        self.0
    }
}
#[rustfmt::skip]
impl From<ErrorReport> for OperationFailed {
    fn from(payload: ErrorReport) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl IntentSubscriptionOpened {
    pub fn new(payload: IntentSubscription) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &IntentSubscription {
        &self.0
    }
    pub fn into_payload(self) -> IntentSubscription {
        self.0
    }
}
#[rustfmt::skip]
impl From<IntentSubscription> for IntentSubscriptionOpened {
    fn from(payload: IntentSubscription) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RemovalCandidatesCollected {
    pub fn new(payload: RemovalCandidatesCollection) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RemovalCandidatesCollection {
        &self.0
    }
    pub fn into_payload(self) -> RemovalCandidatesCollection {
        self.0
    }
}
#[rustfmt::skip]
impl From<RemovalCandidatesCollection> for RemovalCandidatesCollected {
    fn from(payload: RemovalCandidatesCollection) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ObserverTapOpened {
    pub fn new(payload: ObserverSubscription) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ObserverSubscription {
        &self.0
    }
    pub fn into_payload(self) -> ObserverSubscription {
        self.0
    }
}
#[rustfmt::skip]
impl From<ObserverSubscription> for ObserverTapOpened {
    fn from(payload: ObserverSubscription) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ObserverTapClosed {
    pub fn new(payload: ObserverRetraction) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ObserverRetraction {
        &self.0
    }
    pub fn into_payload(self) -> ObserverRetraction {
        self.0
    }
}
#[rustfmt::skip]
impl From<ObserverRetraction> for ObserverTapClosed {
    fn from(payload: ObserverRetraction) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaWriteSet {
    pub fn record(payload: String) -> Self {
        Self::Record(Entry::new(payload))
    }
    pub fn remove(payload: RecordIdentifier) -> Self {
        Self::Remove(Removal::new(payload))
    }
    pub fn change_certainty(payload: Integer) -> Self {
        Self::ChangeCertainty(CertaintyChange::new(payload))
    }
    pub fn bump_importance(payload: Integer) -> Self {
        Self::BumpImportance(ImportanceBump::new(payload))
    }
    pub fn change_record(payload: RecordIdentifier) -> Self {
        Self::ChangeRecord(RecordChange::new(payload))
    }
    pub fn register_referent(payload: String) -> Self {
        Self::RegisterReferent(ReferentRegistration::new(payload))
    }
}

#[rustfmt::skip]
impl EffectCommand {
    pub fn stash(payload: StashRequest) -> Self {
        Self::Stash(payload)
    }
    pub fn classify_state(payload: String) -> Self {
        Self::ClassifyState(Statement::new(payload))
    }
    pub fn record_with_implied_referents(payload: String) -> Self {
        Self::RecordWithImpliedReferents(RecordRequest::new(payload))
    }
    pub fn guard_record(payload: String) -> Self {
        Self::GuardRecord(RecordRequest::new(payload))
    }
    pub fn propose_with_implied_referents(payload: String) -> Self {
        Self::ProposeWithImpliedReferents(Proposal::new(payload))
    }
    pub fn propose(payload: String) -> Self {
        Self::Propose(Proposal::new(payload))
    }
    pub fn clarify(payload: String) -> Self {
        Self::Clarify(Clarification::new(payload))
    }
    pub fn supersede_with_implied_referents(payload: String) -> Self {
        Self::SupersedeWithImpliedReferents(Supersession::new(payload))
    }
    pub fn supersede(payload: String) -> Self {
        Self::Supersede(Supersession::new(payload))
    }
    pub fn retire(payload: String) -> Self {
        Self::Retire(Retirement::new(payload))
    }
    pub fn guard_remove(payload: RecordIdentifier) -> Self {
        Self::GuardRemove(Removal::new(payload))
    }
    pub fn change_record_with_implied_referents(payload: RecordIdentifier) -> Self {
        Self::ChangeRecordWithImpliedReferents(RecordChange::new(payload))
    }
    pub fn guard_change_record(payload: RecordIdentifier) -> Self {
        Self::GuardChangeRecord(RecordChange::new(payload))
    }
    pub fn guard_referent_registration(payload: String) -> Self {
        Self::GuardReferentRegistration(ReferentRegistration::new(payload))
    }
    pub fn open_intent_subscription(payload: String) -> Self {
        Self::OpenIntentSubscription(Query::new(payload))
    }
    pub fn collect_removal_candidates(payload: String) -> Self {
        Self::CollectRemovalCandidates(RemovalCandidateCollection::new(payload))
    }
    pub fn open_observer_tap(payload: String) -> Self {
        Self::OpenObserverTap(ObserverFilter::new(payload))
    }
    pub fn close_observer_tap(payload: Integer) -> Self {
        Self::CloseObserverTap(SubscriptionToken::new(payload))
    }
}

#[rustfmt::skip]
impl EffectOutcome {
    pub fn stashed(payload: StashResult) -> Self {
        Self::Stashed(payload)
    }
    pub fn state_classified(payload: String) -> Self {
        Self::StateClassified(RecordRequest::new(payload))
    }
    pub fn record_referents_settled(payload: String) -> Self {
        Self::RecordReferentsSettled(RecordRequest::new(payload))
    }
    pub fn propose_referents_settled(payload: String) -> Self {
        Self::ProposeReferentsSettled(Proposal::new(payload))
    }
    pub fn supersede_referents_settled(payload: String) -> Self {
        Self::SupersedeReferentsSettled(Supersession::new(payload))
    }
    pub fn change_record_referents_settled(payload: RecordIdentifier) -> Self {
        Self::ChangeRecordReferentsSettled(RecordChange::new(payload))
    }
    pub fn recorded(payload: SemaReceipt) -> Self {
        Self::Recorded(payload)
    }
    pub fn proposed(payload: SemaReceipt) -> Self {
        Self::Proposed(payload)
    }
    pub fn clarified(payload: Boolean) -> Self {
        Self::Clarified(ClarificationReceipt::new(payload))
    }
    pub fn superseded(payload: Boolean) -> Self {
        Self::Superseded(SupersessionReceipt::new(payload))
    }
    pub fn retired(payload: Boolean) -> Self {
        Self::Retired(RetirementReceipt::new(payload))
    }
    pub fn removed(payload: Boolean) -> Self {
        Self::Removed(RemoveReceipt::new(payload))
    }
    pub fn record_changed(payload: Boolean) -> Self {
        Self::RecordChanged(RecordChangeReceipt::new(payload))
    }
    pub fn guardian_rejected(payload: GuardianRejection) -> Self {
        Self::GuardianRejected(payload)
    }
    pub fn referent_registered(payload: Boolean) -> Self {
        Self::ReferentRegistered(ReferentRegistrationReceipt::new(payload))
    }
    pub fn referent_guardian_rejected(payload: ReferentGuardianRejection) -> Self {
        Self::ReferentGuardianRejected(payload)
    }
    pub fn operation_failed(payload: String) -> Self {
        Self::OperationFailed(ErrorReport::new(payload))
    }
    pub fn intent_subscription_opened(payload: SubscriptionToken) -> Self {
        Self::IntentSubscriptionOpened(IntentSubscription::new(payload))
    }
    pub fn removal_candidates_collected(payload: Integer) -> Self {
        Self::RemovalCandidatesCollected(RemovalCandidatesCollection::new(payload))
    }
    pub fn observer_tap_opened(payload: SubscriptionToken) -> Self {
        Self::ObserverTapOpened(ObserverSubscription::new(payload))
    }
    pub fn observer_tap_closed(payload: SubscriptionToken) -> Self {
        Self::ObserverTapClosed(ObserverRetraction::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn signal_arrived(payload: String) -> Self {
        Self::SignalArrived(SignalInput::new(payload))
    }
    pub fn sema_write_completed(payload: Boolean) -> Self {
        Self::SemaWriteCompleted(SemaWriteOutput::new(payload))
    }
    pub fn sema_read_completed(payload: Integer) -> Self {
        Self::SemaReadCompleted(SemaReadOutput::new(payload))
    }
    pub fn effect_completed(payload: EffectOutcome) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn reply_to_signal(payload: String) -> Self {
        Self::ReplyToSignal(SignalOutput::new(payload))
    }
    pub fn command_sema_write(payload: SemaWriteSet) -> Self {
        Self::CommandSemaWrite(payload)
    }
    pub fn command_sema_read(payload: String) -> Self {
        Self::CommandSemaRead(SemaReadInput::new(payload))
    }
    pub fn command_effect(payload: EffectCommand) -> Self {
        Self::CommandEffect(payload)
    }
    pub fn r#continue(payload: Input) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
impl From<Entry> for SemaWriteSet {
    fn from(payload: Entry) -> Self {
        Self::Record(payload)
    }
}

#[rustfmt::skip]
impl From<Removal> for SemaWriteSet {
    fn from(payload: Removal) -> Self {
        Self::Remove(payload)
    }
}

#[rustfmt::skip]
impl From<CertaintyChange> for SemaWriteSet {
    fn from(payload: CertaintyChange) -> Self {
        Self::ChangeCertainty(payload)
    }
}

#[rustfmt::skip]
impl From<ImportanceBump> for SemaWriteSet {
    fn from(payload: ImportanceBump) -> Self {
        Self::BumpImportance(payload)
    }
}

#[rustfmt::skip]
impl From<RecordChange> for SemaWriteSet {
    fn from(payload: RecordChange) -> Self {
        Self::ChangeRecord(payload)
    }
}

#[rustfmt::skip]
impl From<ReferentRegistration> for SemaWriteSet {
    fn from(payload: ReferentRegistration) -> Self {
        Self::RegisterReferent(payload)
    }
}

#[rustfmt::skip]
impl From<StashRequest> for EffectCommand {
    fn from(payload: StashRequest) -> Self {
        Self::Stash(payload)
    }
}

#[rustfmt::skip]
impl From<Statement> for EffectCommand {
    fn from(payload: Statement) -> Self {
        Self::ClassifyState(payload)
    }
}

#[rustfmt::skip]
impl From<Clarification> for EffectCommand {
    fn from(payload: Clarification) -> Self {
        Self::Clarify(payload)
    }
}

#[rustfmt::skip]
impl From<Retirement> for EffectCommand {
    fn from(payload: Retirement) -> Self {
        Self::Retire(payload)
    }
}

#[rustfmt::skip]
impl From<Removal> for EffectCommand {
    fn from(payload: Removal) -> Self {
        Self::GuardRemove(payload)
    }
}

#[rustfmt::skip]
impl From<ReferentRegistration> for EffectCommand {
    fn from(payload: ReferentRegistration) -> Self {
        Self::GuardReferentRegistration(payload)
    }
}

#[rustfmt::skip]
impl From<Query> for EffectCommand {
    fn from(payload: Query) -> Self {
        Self::OpenIntentSubscription(payload)
    }
}

#[rustfmt::skip]
impl From<RemovalCandidateCollection> for EffectCommand {
    fn from(payload: RemovalCandidateCollection) -> Self {
        Self::CollectRemovalCandidates(payload)
    }
}

#[rustfmt::skip]
impl From<ObserverFilter> for EffectCommand {
    fn from(payload: ObserverFilter) -> Self {
        Self::OpenObserverTap(payload)
    }
}

#[rustfmt::skip]
impl From<SubscriptionToken> for EffectCommand {
    fn from(payload: SubscriptionToken) -> Self {
        Self::CloseObserverTap(payload)
    }
}

#[rustfmt::skip]
impl From<StashResult> for EffectOutcome {
    fn from(payload: StashResult) -> Self {
        Self::Stashed(payload)
    }
}

#[rustfmt::skip]
impl From<Proposal> for EffectOutcome {
    fn from(payload: Proposal) -> Self {
        Self::ProposeReferentsSettled(payload)
    }
}

#[rustfmt::skip]
impl From<Supersession> for EffectOutcome {
    fn from(payload: Supersession) -> Self {
        Self::SupersedeReferentsSettled(payload)
    }
}

#[rustfmt::skip]
impl From<RecordChange> for EffectOutcome {
    fn from(payload: RecordChange) -> Self {
        Self::ChangeRecordReferentsSettled(payload)
    }
}

#[rustfmt::skip]
impl From<ClarificationReceipt> for EffectOutcome {
    fn from(payload: ClarificationReceipt) -> Self {
        Self::Clarified(payload)
    }
}

#[rustfmt::skip]
impl From<SupersessionReceipt> for EffectOutcome {
    fn from(payload: SupersessionReceipt) -> Self {
        Self::Superseded(payload)
    }
}

#[rustfmt::skip]
impl From<RetirementReceipt> for EffectOutcome {
    fn from(payload: RetirementReceipt) -> Self {
        Self::Retired(payload)
    }
}

#[rustfmt::skip]
impl From<RemoveReceipt> for EffectOutcome {
    fn from(payload: RemoveReceipt) -> Self {
        Self::Removed(payload)
    }
}

#[rustfmt::skip]
impl From<RecordChangeReceipt> for EffectOutcome {
    fn from(payload: RecordChangeReceipt) -> Self {
        Self::RecordChanged(payload)
    }
}

#[rustfmt::skip]
impl From<GuardianRejection> for EffectOutcome {
    fn from(payload: GuardianRejection) -> Self {
        Self::GuardianRejected(payload)
    }
}

#[rustfmt::skip]
impl From<ReferentRegistrationReceipt> for EffectOutcome {
    fn from(payload: ReferentRegistrationReceipt) -> Self {
        Self::ReferentRegistered(payload)
    }
}

#[rustfmt::skip]
impl From<ReferentGuardianRejection> for EffectOutcome {
    fn from(payload: ReferentGuardianRejection) -> Self {
        Self::ReferentGuardianRejected(payload)
    }
}

#[rustfmt::skip]
impl From<ErrorReport> for EffectOutcome {
    fn from(payload: ErrorReport) -> Self {
        Self::OperationFailed(payload)
    }
}

#[rustfmt::skip]
impl From<IntentSubscription> for EffectOutcome {
    fn from(payload: IntentSubscription) -> Self {
        Self::IntentSubscriptionOpened(payload)
    }
}

#[rustfmt::skip]
impl From<RemovalCandidatesCollection> for EffectOutcome {
    fn from(payload: RemovalCandidatesCollection) -> Self {
        Self::RemovalCandidatesCollected(payload)
    }
}

#[rustfmt::skip]
impl From<ObserverSubscription> for EffectOutcome {
    fn from(payload: ObserverSubscription) -> Self {
        Self::ObserverTapOpened(payload)
    }
}

#[rustfmt::skip]
impl From<ObserverRetraction> for EffectOutcome {
    fn from(payload: ObserverRetraction) -> Self {
        Self::ObserverTapClosed(payload)
    }
}

#[rustfmt::skip]
impl From<SignalInput> for Input {
    fn from(payload: SignalInput) -> Self {
        Self::SignalArrived(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteOutput> for Input {
    fn from(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadOutput> for Input {
    fn from(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<EffectOutcome> for Input {
    fn from(payload: EffectOutcome) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SignalOutput> for Output {
    fn from(payload: SignalOutput) -> Self {
        Self::ReplyToSignal(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteSet> for Output {
    fn from(payload: SemaWriteSet) -> Self {
        Self::CommandSemaWrite(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadInput> for Output {
    fn from(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(payload)
    }
}

#[rustfmt::skip]
impl From<EffectCommand> for Output {
    fn from(payload: EffectCommand) -> Self {
        Self::CommandEffect(payload)
    }
}

#[rustfmt::skip]
impl From<Input> for Output {
    fn from(payload: Input) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(Integer);
#[rustfmt::skip]
impl OriginRoute {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
