//! Strict bootstrap Interface generation.
//!
//! This lane begins after the sole naming authority has authenticated an exact
//! bootstrap transaction. It does not accept source text, a decoded document,
//! `SchemaSource`, `TrueSchema`, or caller-invented name bindings. The matching
//! reader is revalidated by Nomos, and Rust is projected from the resulting
//! `WholeLogos` through a caller-supplied sealed Rust vocabulary and explicit
//! external type-path resolver.

use std::path::PathBuf;

use core_ethos::bootstrap::{BootstrapBody, EthosKind};
use core_nomos::{BootstrapSliceOneLowering, BootstrapSliceOneLoweringError};
use rust_logos::{RustLogos, RustTypePathResolver};
use sema_translator::bootstrap::VerifiedBootstrapAssembly;

use crate::build::{BuildError, FreshnessCheck, GeneratedArtifact};

/// Marker placed ahead of every Rust artifact emitted by the strict bootstrap
/// Interface lane.
pub const BOOTSTRAP_INTERFACE_GENERATED_MARKER: &str =
    "// @generated by schema-rust from an authority-verified bootstrap Interface\n\n";

/// One complete, explicit bootstrap Interface generation request.
///
/// `assembly` owns the verified encoded-name resolver. `rust` owns the sealed
/// structural Rust vocabulary. `rust_types` owns every external Rust path.
/// This boundary creates none of those inputs and performs no spelling-based
/// identity or path inference.
pub struct BootstrapInterfaceGeneration<'a> {
    assembly: &'a VerifiedBootstrapAssembly,
    rust: &'a RustLogos,
    rust_types: &'a dyn RustTypePathResolver,
    source_path: PathBuf,
    rust_path: PathBuf,
}

impl<'a> BootstrapInterfaceGeneration<'a> {
    /// Seat the complete authority, Nomos, and Rust projection inputs.
    pub fn new(
        assembly: &'a VerifiedBootstrapAssembly,
        rust: &'a RustLogos,
        rust_types: &'a dyn RustTypePathResolver,
        source_path: impl Into<PathBuf>,
        rust_path: impl Into<PathBuf>,
    ) -> Self {
        Self {
            assembly,
            rust,
            rust_types,
            source_path: source_path.into(),
            rust_path: rust_path.into(),
        }
    }

    /// Revalidate and lower the exact prepared transaction, then structurally
    /// project deterministic Rust from `WholeLogos`.
    pub fn generate(
        &self,
    ) -> Result<GeneratedBootstrapInterface, BootstrapInterfaceGenerationError> {
        match &self.assembly.transaction().decoded().document.body {
            BootstrapBody::Interface(_) => {}
            BootstrapBody::Nexus(_) => {
                return Err(BootstrapInterfaceGenerationError::WrongFileKind {
                    found: EthosKind::Nexus,
                });
            }
            BootstrapBody::Sema(_) => {
                return Err(BootstrapInterfaceGenerationError::WrongFileKind {
                    found: EthosKind::Sema,
                });
            }
        }

        let logos = BootstrapSliceOneLowering::new()
            .lower(self.assembly.reader(), self.assembly.transaction())?;
        let projected =
            self.rust
                .emit_with_type_paths(&logos, self.assembly.resolver(), self.rust_types)?;
        let mut rust_source =
            String::with_capacity(BOOTSTRAP_INTERFACE_GENERATED_MARKER.len() + projected.len());
        rust_source.push_str(BOOTSTRAP_INTERFACE_GENERATED_MARKER);
        rust_source.push_str(&projected);

        Ok(GeneratedBootstrapInterface {
            source: GeneratedArtifact::new(
                self.source_path.clone(),
                self.assembly.canonical_source(),
            ),
            rust: GeneratedArtifact::new(self.rust_path.clone(), rust_source),
        })
    }
}

/// Canonical source and Rust projections of one validated Interface
/// transaction.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedBootstrapInterface {
    source: GeneratedArtifact,
    rust: GeneratedArtifact,
}

impl GeneratedBootstrapInterface {
    /// Canonical source projection, including its checked path.
    pub const fn source(&self) -> &GeneratedArtifact {
        &self.source
    }

    /// Canonical Rust projection, including its checked path.
    pub const fn rust(&self) -> &GeneratedArtifact {
        &self.rust
    }

    /// Require both checked artifacts to equal their canonical projections.
    pub fn assert_checked_in(&self) -> Result<(), BuildError> {
        let check = FreshnessCheck::check_only();
        self.source.check_with(&check)?;
        self.rust.check_with(&check)
    }

    /// Check both projections, or update both when the explicit environment
    /// variable is present.
    pub fn write_or_check(
        &self,
        update_environment_variable: impl Into<String>,
    ) -> Result<(), BuildError> {
        let check = FreshnessCheck::from_environment(update_environment_variable);
        self.source.check_with(&check)?;
        self.rust.check_with(&check)
    }
}

/// Exact refusal from the strict bootstrap Interface generation lane.
#[derive(Debug, thiserror::Error)]
pub enum BootstrapInterfaceGenerationError {
    /// Only the provisional Interface file kind belongs to this generator.
    #[error("bootstrap Interface generation received {found:?} source")]
    WrongFileKind { found: EthosKind },
    /// Nomos rejected the still-authority-branded transaction.
    #[error(transparent)]
    Lowering(#[from] BootstrapSliceOneLoweringError),
    /// The canonical structural Rust projection refused an explicit input.
    #[error(transparent)]
    RustProjection(#[from] rust_logos::Error),
}
