//! Strict bootstrap generation through the unified authority pipeline.
//!
//! One orchestration path accepts any authority-sealed bootstrap assembly,
//! lowers it through Nomos, projects deterministic Rust, and returns an
//! `ArtifactSet` carrying both canonical Ethos source and generated Rust.
//! `CommitBootstrap` then installs the complete set atomically — all or
//! nothing — eliminating the partial-install window that previously existed
//! between sequential source and Rust writes.
//!
//! Pipeline: PlanText -> AuthorizePlan -> Lower -> Render -> CommitBootstrap
//!
// psyche-grasp: slightly-reviewed (2026-08-07)

use std::{
    fs,
    io::ErrorKind,
    path::PathBuf,
};

use core_ethos::bootstrap::{BootstrapBody, EthosKind, InterfaceRole};
use core_nomos::{
    BootstrapSliceOneLowering, BootstrapSliceOneLoweringError, ExternalStorageProvenance,
    InterfaceRoleTraitIdentities,
};
use rust_logos::{RustLogos, RustTypePathResolver};
use sema_translator::bootstrap::AuthorizedBootstrap;

use crate::build::{BuildError, GeneratedArtifact};

/// Marker placed as the first line of every Rust artifact emitted by the
/// strict bootstrap generation pipeline.
pub const BOOTSTRAP_GENERATED_MARKER: &str =
    "// @generated by schema-rust from an authority-verified bootstrap source\n";

/// Prefix of the source-digest comment line embedded in every Rust artifact
/// immediately after `BOOTSTRAP_GENERATED_MARKER`.
const SOURCE_DIGEST_PREFIX: &str = "// source-digest: blake3:";

/// One complete, explicit bootstrap generation request.
///
/// `assembly` owns the verified read-only name view. `rust_types` owns every
/// external Rust path. `external_storage` carries owner-and-revision-bound
/// archive provenance for every nonlocal storage leaf. This boundary creates
/// or infers none of those inputs.
///
/// The same type handles Interface and Sema file kinds. Core Nomos dispatches
/// the lowering; callers supply only authority-sealed state.
// psyche-grasp: slightly-reviewed (2026-08-07)
pub struct BootstrapGeneration<'a> {
    assembly: &'a AuthorizedBootstrap,
    rust: &'a RustLogos,
    rust_types: &'a dyn RustTypePathResolver,
    external_storage: &'a [ExternalStorageProvenance],
    role_traits: Option<&'a InterfaceRoleTraitIdentities>,
    source_path: PathBuf,
    rust_path: PathBuf,
}

impl<'a> BootstrapGeneration<'a> {
    /// Seat the complete authority, Nomos, and Rust projection inputs.
    pub fn new(
        assembly: &'a AuthorizedBootstrap,
        rust: &'a RustLogos,
        rust_types: &'a dyn RustTypePathResolver,
        external_storage: &'a [ExternalStorageProvenance],
        source_path: impl Into<PathBuf>,
        rust_path: impl Into<PathBuf>,
    ) -> Self {
        Self {
            assembly,
            rust,
            rust_types,
            external_storage,
            role_traits: None,
            source_path: source_path.into(),
            rust_path: rust_path.into(),
        }
    }

    /// Supply the positional role trait identities for Interface generation.
    ///
    /// When set, the Interface lowering emits trait implementations mapping
    /// each role-section entry to its universal trait (Input/Output/Refusal/
    /// Stream). Without this, Interface sources with role entries are refused.
    pub fn with_role_traits(mut self, role_traits: &'a InterfaceRoleTraitIdentities) -> Self {
        self.role_traits = Some(role_traits);
        self
    }

    /// Revalidate and lower the exact prepared transaction through the
    /// appropriate Nomos path, then structurally project deterministic Rust
    /// from `WholeLogos`.
    pub fn generate(&self) -> Result<ArtifactSet, BootstrapGenerationError> {
        let body = &self.assembly.transaction().decoded().document.body;
        let logos = match body {
            BootstrapBody::Interface(_) => match self.role_traits {
                Some(role_traits) => BootstrapSliceOneLowering::new().lower_interface(
                    self.assembly.reader(),
                    self.assembly.transaction(),
                    role_traits,
                )?,
                None => BootstrapSliceOneLowering::new()
                    .lower(self.assembly.reader(), self.assembly.transaction())?,
            },
            BootstrapBody::Sema(_) => BootstrapSliceOneLowering::new().lower_sema(
                self.assembly.reader(),
                self.assembly.transaction(),
                self.external_storage,
            )?,
            BootstrapBody::Nexus(_) => {
                return Err(BootstrapGenerationError::UnsupportedFileKind {
                    found: EthosKind::Nexus,
                });
            }
        };
        // When role traits are present, configure the emitter to generate
        // Display and std::error::Error for types implementing the Refusal
        // role trait. The Refusal trait requires std::error::Error, which
        // the emitter satisfies through a derive(Debug) preamble plus these
        // generated implementations.
        let configured_rust;
        let emitter: &RustLogos = match self.role_traits {
            Some(role_traits) => {
                configured_rust = RustLogos::new().with_refusal_display_trait(
                    *role_traits.trait_identity(InterfaceRole::Refusal),
                );
                &configured_rust
            }
            None => self.rust,
        };
        let projected =
            emitter.emit_with_type_paths(&logos, self.assembly.name_view(), self.rust_types)?;
        let canonical_source = self.assembly.canonical_source();
        let source_digest_hex =
            format!("{}", blake3::hash(canonical_source.as_bytes()).to_hex());
        let mut rust_source = String::with_capacity(
            BOOTSTRAP_GENERATED_MARKER.len()
                + SOURCE_DIGEST_PREFIX.len()
                + source_digest_hex.len()
                + 2 // newline after digest + blank separator line
                + projected.len(),
        );
        rust_source.push_str(BOOTSTRAP_GENERATED_MARKER);
        rust_source.push_str(SOURCE_DIGEST_PREFIX);
        rust_source.push_str(&source_digest_hex);
        rust_source.push('\n');
        rust_source.push('\n');
        rust_source.push_str(&projected);

        Ok(ArtifactSet {
            source: GeneratedArtifact::new(
                self.source_path.clone(),
                canonical_source.to_owned(),
            ),
            rust: GeneratedArtifact::new(self.rust_path.clone(), rust_source),
        })
    }
}

/// Canonical source and Rust projections of one validated bootstrap
/// transaction.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ArtifactSet {
    source: GeneratedArtifact,
    rust: GeneratedArtifact,
}

impl ArtifactSet {
    /// Canonical source projection, including its checked path.
    pub const fn source(&self) -> &GeneratedArtifact {
        &self.source
    }

    /// Canonical Rust projection, including its checked path.
    pub const fn rust(&self) -> &GeneratedArtifact {
        &self.rust
    }
}

/// Atomic installation of bootstrap artifact sets.
///
/// Gathers one or more `ArtifactSet` values and commits them all or nothing:
/// every file is written to its sibling `.pending` path first; only after all
/// temporary writes succeed are the files renamed into place. A kill between
/// renames leaves at most orphaned `.pending` files — the canonical paths
/// remain unchanged from their prior state.
pub struct CommitBootstrap {
    sets: Vec<ArtifactSet>,
}

impl CommitBootstrap {
    /// Build a commit from a single artifact set.
    pub fn single(set: ArtifactSet) -> Self {
        Self { sets: vec![set] }
    }

    /// Add one generated artifact set to this atomic commit.
    pub fn add(&mut self, set: ArtifactSet) {
        self.sets.push(set);
    }

    /// Verify every source artifact is fresh by comparing its on-disk blake3
    /// digest to the digest embedded in the corresponding Rust artifact.
    ///
    /// This check is deterministic: it does not regenerate identities. It
    /// reads both committed files from disk and compares a stored digest in
    /// the Rust artifact against a freshly computed digest of the source
    /// artifact. A mismatch, missing digest, or absent file is treated as
    /// stale.
    pub fn assert_checked_in(&self) -> Result<(), BuildError> {
        for set in &self.sets {
            let stored = Self::extract_stored_source_digest(&set.rust)?
                .ok_or_else(|| BuildError::StaleGeneratedArtifact {
                    path: set.source.path().to_path_buf(),
                })?;
            let on_disk = set
                .source
                .on_disk_blake3_hex()?
                .ok_or_else(|| BuildError::StaleGeneratedArtifact {
                    path: set.source.path().to_path_buf(),
                })?;
            if stored != on_disk {
                return Err(BuildError::StaleGeneratedArtifact {
                    path: set.source.path().to_path_buf(),
                });
            }
        }
        Ok(())
    }

    /// Extract the blake3 source digest stored in a Rust artifact's on-disk
    /// content, returning `None` when the file is absent or carries no valid
    /// digest line.
    fn extract_stored_source_digest(
        rust_artifact: &GeneratedArtifact,
    ) -> Result<Option<String>, BuildError> {
        let content = match fs::read_to_string(rust_artifact.path()) {
            Ok(c) => c,
            Err(error) if error.kind() == ErrorKind::NotFound => return Ok(None),
            Err(source) => {
                return Err(BuildError::ReadGeneratedArtifact {
                    path: rust_artifact.path().to_path_buf(),
                    source,
                })
            }
        };
        let digest_line = content.lines().nth(1).unwrap_or("");
        let hex = match digest_line.strip_prefix(SOURCE_DIGEST_PREFIX) {
            Some(h) => h,
            None => return Ok(None),
        };
        if hex.len() == 64 && hex.bytes().all(|b| b.is_ascii_hexdigit()) {
            Ok(Some(hex.to_owned()))
        } else {
            Ok(None)
        }
    }

    /// Install all artifacts atomically, or verify freshness when the
    /// environment variable is absent.
    ///
    /// When `update_environment_variable` is set in the process environment,
    /// all artifacts are written to `.pending` siblings, then renamed into
    /// place in a tight sequence. When it is absent, every artifact must
    /// already match its canonical content.
    pub fn write_or_check(
        &self,
        update_environment_variable: impl AsRef<str>,
    ) -> Result<(), BuildError> {
        if std::env::var_os(update_environment_variable.as_ref()).is_some() {
            self.commit()
        } else {
            self.assert_checked_in()
        }
    }

    /// Install all artifacts atomically.
    ///
    /// Every file is written to its sibling `.pending` path first. Only after
    /// all temporary writes succeed are the files renamed into place in a
    /// tight sequence. A kill before the rename phase completes leaves at most
    /// orphaned `.pending` files; the canonical paths remain unchanged.
    pub fn commit(&self) -> Result<(), BuildError> {
        // Phase 1: write every artifact to its pending path.
        let mut written: Vec<(&GeneratedArtifact, PathBuf)> = Vec::new();
        for set in &self.sets {
            for artifact in [&set.source, &set.rust] {
                let target = artifact.pending_path();
                artifact.write_to(&target)?;
                written.push((artifact, target));
            }
        }

        // Phase 2: rename all pending files into place (tight sequence).
        for (artifact, pending) in &written {
            std::fs::rename(pending, artifact.path()).map_err(|source| {
                BuildError::WriteGeneratedArtifact {
                    path: artifact.path().to_path_buf(),
                    source,
                }
            })?;
        }

        Ok(())
    }
}

/// Exact refusal from the unified bootstrap generation pipeline.
#[derive(Debug, thiserror::Error)]
pub enum BootstrapGenerationError {
    /// The Nexus file kind is not yet supported by the generation pipeline.
    #[error("bootstrap generation does not support {found:?} source")]
    UnsupportedFileKind { found: EthosKind },
    /// Nomos rejected the authority-branded transaction.
    #[error(transparent)]
    Lowering(#[from] BootstrapSliceOneLoweringError),
    /// The canonical structural Rust projection refused an explicit input.
    #[error(transparent)]
    RustProjection(#[from] rust_logos::Error),
}
