//! Strict bootstrap generation through the unified authority pipeline.
//!
//! One orchestration path accepts any authority-sealed bootstrap assembly,
//! lowers it through Nomos, projects deterministic Rust, and returns an
//! `ArtifactSet` carrying both canonical Ethos source and generated Rust.
//! `CommitBootstrap` then installs the complete set atomically — all or
//! nothing — eliminating the partial-install window that previously existed
//! between sequential source and Rust writes.
//!
//! Pipeline: PlanText -> AuthorizePlan -> Lower -> Render -> CommitBootstrap
//!
// psyche-grasp: slightly-reviewed (2026-08-07)

use std::path::PathBuf;

use core_ethos::bootstrap::{BootstrapBody, EthosKind};
use core_nomos::{
    BootstrapSliceOneLowering, BootstrapSliceOneLoweringError, ExternalStorageProvenance,
};
use rust_logos::{RustLogos, RustTypePathResolver};
use sema_translator::bootstrap::AuthorizedBootstrap;

use crate::build::{BuildError, GeneratedArtifact};

/// Marker placed ahead of every Rust artifact emitted by the strict bootstrap
/// generation pipeline.
pub const BOOTSTRAP_GENERATED_MARKER: &str =
    "// @generated by schema-rust from an authority-verified bootstrap source\n\n";

/// One complete, explicit bootstrap generation request.
///
/// `assembly` owns the verified read-only name view. `rust_types` owns every
/// external Rust path. `external_storage` carries owner-and-revision-bound
/// archive provenance for every nonlocal storage leaf. This boundary creates
/// or infers none of those inputs.
///
/// The same type handles Interface and Sema file kinds. Core Nomos dispatches
/// the lowering; callers supply only authority-sealed state.
pub struct BootstrapGeneration<'a> {
    assembly: &'a AuthorizedBootstrap,
    rust: &'a RustLogos,
    rust_types: &'a dyn RustTypePathResolver,
    external_storage: &'a [ExternalStorageProvenance],
    source_path: PathBuf,
    rust_path: PathBuf,
}

impl<'a> BootstrapGeneration<'a> {
    /// Seat the complete authority, Nomos, and Rust projection inputs.
    pub fn new(
        assembly: &'a AuthorizedBootstrap,
        rust: &'a RustLogos,
        rust_types: &'a dyn RustTypePathResolver,
        external_storage: &'a [ExternalStorageProvenance],
        source_path: impl Into<PathBuf>,
        rust_path: impl Into<PathBuf>,
    ) -> Self {
        Self {
            assembly,
            rust,
            rust_types,
            external_storage,
            source_path: source_path.into(),
            rust_path: rust_path.into(),
        }
    }

    /// Revalidate and lower the exact prepared transaction through the
    /// appropriate Nomos path, then structurally project deterministic Rust
    /// from `WholeLogos`.
    pub fn generate(&self) -> Result<ArtifactSet, BootstrapGenerationError> {
        let body = &self.assembly.transaction().decoded().document.body;
        let logos = match body {
            BootstrapBody::Interface(_) => BootstrapSliceOneLowering::new()
                .lower(self.assembly.reader(), self.assembly.transaction())?,
            BootstrapBody::Sema(_) => BootstrapSliceOneLowering::new().lower_sema(
                self.assembly.reader(),
                self.assembly.transaction(),
                self.external_storage,
            )?,
            BootstrapBody::Nexus(_) => {
                return Err(BootstrapGenerationError::UnsupportedFileKind {
                    found: EthosKind::Nexus,
                });
            }
        };
        let projected =
            self.rust
                .emit_with_type_paths(&logos, self.assembly.name_view(), self.rust_types)?;
        let mut rust_source =
            String::with_capacity(BOOTSTRAP_GENERATED_MARKER.len() + projected.len());
        rust_source.push_str(BOOTSTRAP_GENERATED_MARKER);
        rust_source.push_str(&projected);

        Ok(ArtifactSet {
            source: GeneratedArtifact::new(
                self.source_path.clone(),
                self.assembly.canonical_source().to_owned(),
            ),
            rust: GeneratedArtifact::new(self.rust_path.clone(), rust_source),
        })
    }
}

/// Canonical source and Rust projections of one validated bootstrap
/// transaction.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ArtifactSet {
    source: GeneratedArtifact,
    rust: GeneratedArtifact,
}

impl ArtifactSet {
    /// Canonical source projection, including its checked path.
    pub const fn source(&self) -> &GeneratedArtifact {
        &self.source
    }

    /// Canonical Rust projection, including its checked path.
    pub const fn rust(&self) -> &GeneratedArtifact {
        &self.rust
    }
}

/// Atomic installation of bootstrap artifact sets.
///
/// Gathers one or more `ArtifactSet` values and commits them all or nothing:
/// every file is written to its sibling `.pending` path first; only after all
/// temporary writes succeed are the files renamed into place. A kill between
/// renames leaves at most orphaned `.pending` files — the canonical paths
/// remain unchanged from their prior state.
pub struct CommitBootstrap {
    sets: Vec<ArtifactSet>,
}

impl CommitBootstrap {
    /// Build a commit from a single artifact set.
    pub fn single(set: ArtifactSet) -> Self {
        Self { sets: vec![set] }
    }

    /// Add one generated artifact set to this atomic commit.
    pub fn add(&mut self, set: ArtifactSet) {
        self.sets.push(set);
    }

    /// Require every artifact in every set to match its checked-in content.
    pub fn assert_checked_in(&self) -> Result<(), BuildError> {
        for set in &self.sets {
            set.source.assert_matches_existing()?;
            set.rust.assert_matches_existing()?;
        }
        Ok(())
    }

    /// Install all artifacts atomically, or verify freshness when the
    /// environment variable is absent.
    ///
    /// When `update_environment_variable` is set in the process environment,
    /// all artifacts are written to `.pending` siblings, then renamed into
    /// place in a tight sequence. When it is absent, every artifact must
    /// already match its canonical content.
    pub fn write_or_check(
        &self,
        update_environment_variable: impl AsRef<str>,
    ) -> Result<(), BuildError> {
        if std::env::var_os(update_environment_variable.as_ref()).is_some() {
            self.commit()
        } else {
            self.assert_checked_in()
        }
    }

    /// Install all artifacts atomically.
    ///
    /// Every file is written to its sibling `.pending` path first. Only after
    /// all temporary writes succeed are the files renamed into place in a
    /// tight sequence. A kill before the rename phase completes leaves at most
    /// orphaned `.pending` files; the canonical paths remain unchanged.
    pub fn commit(&self) -> Result<(), BuildError> {
        // Phase 1: write every artifact to its pending path.
        let mut written: Vec<(&GeneratedArtifact, PathBuf)> = Vec::new();
        for set in &self.sets {
            for artifact in [&set.source, &set.rust] {
                let target = artifact.pending_path();
                artifact.write_to(&target)?;
                written.push((artifact, target));
            }
        }

        // Phase 2: rename all pending files into place (tight sequence).
        for (artifact, pending) in &written {
            std::fs::rename(pending, artifact.path()).map_err(|source| {
                BuildError::WriteGeneratedArtifact {
                    path: artifact.path().to_path_buf(),
                    source,
                }
            })?;
        }

        Ok(())
    }
}

/// Exact refusal from the unified bootstrap generation pipeline.
#[derive(Debug, thiserror::Error)]
pub enum BootstrapGenerationError {
    /// The Nexus file kind is not yet supported by the generation pipeline.
    #[error("bootstrap generation does not support {found:?} source")]
    UnsupportedFileKind { found: EthosKind },
    /// Nomos rejected the authority-branded transaction.
    #[error(transparent)]
    Lowering(#[from] BootstrapSliceOneLoweringError),
    /// The canonical structural Rust projection refused an explicit input.
    #[error(transparent)]
    RustProjection(#[from] rust_logos::Error),
}
